<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Manfaat Beasiswa JKM_tipe_manfaat</name>
   <tag></tag>
   <elementGuidId>5318fff8-9c2a-4a14-840f-68fab5530c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='B004']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#B004</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69fcdf10-7c12-458a-8633-c8e492f2f051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5932138b-7ca8-4d07-8cb6-d64fb1b7069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B004</value>
      <webElementGuid>20fc7dc2-d0fe-4082-af92-64de5b1af711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipe_manfaat</value>
      <webElementGuid>0abb1d9d-bbba-409b-94c8-94bf139e45df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B004</value>
      <webElementGuid>b38d35f6-2a35-444c-955e-458564c7dd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>handleSelectChange(this);</value>
      <webElementGuid>87c430cb-9f96-4d31-8d2b-5ac37a5231dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B004&quot;)</value>
      <webElementGuid>8afff196-ca91-42f2-828d-2133927c6363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/manual/radio button jkm/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1014-Perekaman Data Biometrik Pelapor_form</value>
      <webElementGuid>5accddd9-0bbb-4685-9300-a8e0a7bb940f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='B004']</value>
      <webElementGuid>309b29c6-9c02-4166-aea6-1e43ede4e58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetDataRekening']/div/div/table/tbody/tr/td/div[3]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>d16305ea-260a-4511-b7c2-c1aebf8c45e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>7264cb07-a9dd-424c-8805-eb8b403e4d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'B004' and @name = 'tipe_manfaat']</value>
      <webElementGuid>3986238c-d87f-4a10-9d9b-168fb48e763d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
