<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KATEGORI_rg_kategori</name>
   <tag></tag>
   <elementGuidId>1080cfc8-4baf-4523-835b-f993ea1ae89f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rg_subkategori</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rg_subkategori']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdc8f25c-9ce3-4533-b698-2ccb338c0ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>29612e59-9c8b-409b-ae89-e600489a7534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rg_kategori</value>
      <webElementGuid>ac02cc6a-ad27-44a7-be8b-402690b6876f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rg_subkategori</value>
      <webElementGuid>09243ed3-96f8-41d9-a4e5-92084a4353aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>2f8008aa-8a50-4f38-b01d-288eaade75b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>filter('', 'Y', '', '', '')</value>
      <webElementGuid>bba4f36f-5f7e-46dd-b7ca-d785e84a7877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rg_subkategori&quot;)</value>
      <webElementGuid>9701bc86-8b3d-437b-a0d1-81c911caab9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/2 sub kategori/1 sub kategori validasi - new/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>39f41e96-33b5-48ed-9083-1881b3822849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rg_subkategori']</value>
      <webElementGuid>ace08dcd-122b-49ea-9c17-81bcb6437292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div/div[6]/div/input[2]</value>
      <webElementGuid>f7054e3c-822c-4c49-9a91-13523c6fcb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>c9b18b55-c703-47b2-a4bd-f0dc6a38c599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rg_kategori' and @id = 'rg_subkategori']</value>
      <webElementGuid>03bddc2b-eb09-4a71-9477-a2d64d301a76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
