<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK_button-1005-btnIconEl</name>
   <tag></tag>
   <elementGuidId>76649c01-f7af-4b2f-b08c-91de60a05bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1005-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1005-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d7c457e-245e-446f-8ca5-c6bcf02a31e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a5901b37-fdc1-43fb-9949-e16a7873a604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1005-btnIconEl</value>
      <webElementGuid>4389b8b4-7c1f-4d84-8cdd-26e9b90b51b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>49648cb9-8b2b-47c7-b49c-e115d4b7e44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3890d261-32bc-4df4-85e0-4a2a98be579b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1005-btnIconEl&quot;)</value>
      <webElementGuid>b02def32-95b0-4010-8fdc-df2eab6968b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnIconEl']</value>
      <webElementGuid>4cad6307-48aa-4c01-9dda-9f0f27ced388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnEl']/span[2]</value>
      <webElementGuid>924fb676-dee0-47ad-8d01-163aeca7c3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/span/span/span[2]</value>
      <webElementGuid>da99f3b6-9f48-4e1c-9c7c-c6c40da3d37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1005-btnIconEl']</value>
      <webElementGuid>65ddd8df-8b95-4dcd-9c51-7e3796ee7a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
