<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FKAT001 - UMUM EDITED 1 LAGI EDITED EDITED</name>
   <tag></tag>
   <elementGuidId>c3d6fecd-ae4b-49a9-8750-4f8ee993e39e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-kategori0-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-kategori0-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>09a58516-bb5b-45ea-bf1a-50471d13e3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1242057a-5f8a-443f-9479-cdc2a9349957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-kategori0-container</value>
      <webElementGuid>ce22ba7b-e5a1-4abf-adba-cbbb1c1e8677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>28a0313c-da2f-46a6-a188-22552827bd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63ce1cf5-d14a-401e-9f7c-e938ac20fb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>FKAT001 - UMUM EDITED 1 LAGI EDITED EDITED</value>
      <webElementGuid>fe74ccf3-4376-4609-a27e-bea0ff983a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FKAT001 - UMUM EDITED 1 LAGI EDITED EDITED</value>
      <webElementGuid>ab210a59-2663-4b91-9e5c-a5aa2e963af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-kategori0-container&quot;)</value>
      <webElementGuid>0f5e3d5e-b711-4367-9e9d-91aa4edcf350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/2 sub kategori/1 sub kategori validasi - new/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>1e3a3eb0-1814-4366-939f-18c13e89b654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-kategori0-container']</value>
      <webElementGuid>9f837fe3-d332-4e78-a7ef-499077be029b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konten_form']/div[4]/span/span/span/span</value>
      <webElementGuid>1a6c002d-0e4f-4ff1-a75f-c30e92a36f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[17]/following::span[4]</value>
      <webElementGuid>ddbec263-02f5-4955-a61d-b9180968a4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[18]/preceding::span[3]</value>
      <webElementGuid>5e9fbe64-ce35-45a4-9704-cc0a7e582976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/span/span/span</value>
      <webElementGuid>7d1aa8f4-ecbe-46a4-a6f5-d2ef7dd69bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-kategori0-container' and @title = 'FKAT001 - UMUM EDITED 1 LAGI EDITED EDITED' and (text() = 'FKAT001 - UMUM EDITED 1 LAGI EDITED EDITED' or . = 'FKAT001 - UMUM EDITED 1 LAGI EDITED EDITED')]</value>
      <webElementGuid>7555148c-e23f-4473-b945-f2608e076e4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
