<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New</name>
   <tag></tag>
   <elementGuidId>a2709487-8c41-4aeb-97a1-08686182c896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>366ed0bb-88e3-4500-a176-afc4c4a4ddad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_new</value>
      <webElementGuid>65de1e8b-f5bf-40c1-8a3b-91aa1d1c3b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>202718ab-3274-4f3b-8ce4-3406c10e0bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
             New</value>
      <webElementGuid>13a53f54-f1b4-4a7a-9598-c56a4eefd6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_new&quot;)</value>
      <webElementGuid>399407c3-68c9-46ba-ba76-a3feb24d82f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/reset akun dan buka suspend/2 buka suspend/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_LD5001-Perekaman Informasi dan Penga_4f240a</value>
      <webElementGuid>ae6f1dd4-63fc-4f11-947a-0e22c7ec54a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_new']</value>
      <webElementGuid>f2bdee96-8f68-4b2d-8f90-e954cfb2f9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actbutton']/div[2]/div/a</value>
      <webElementGuid>64b10d05-c783-41d7-937c-e471573934cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PEREKAMAN INFORMASI/PENGADUAN'])[1]/preceding::a[1]</value>
      <webElementGuid>1bc32954-c27e-4b96-93a8-77b07099342a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Agenda'])[1]/preceding::a[1]</value>
      <webElementGuid>c4a95b04-df20-4acf-9426-463a56a961e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New']/parent::*</value>
      <webElementGuid>fcae6738-8422-4409-af3e-ff6327d03d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>9cd04e6b-99cf-4863-8772-457c526569d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>dacc7eea-d4ac-49ca-9e23-6f88a8d49ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_new' and @href = 'javascript:void(0)' and (text() = '
             New' or . = '
             New')]</value>
      <webElementGuid>97a06a07-b3d6-46dc-beca-523ef6411e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
