<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_LD5001-Perekaman Informasi dan Penga_4f240a</name>
   <tag></tag>
   <elementGuidId>46043683-3973-47c8-bc78-ca4cbbebe22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>79939e12-7534-476a-b49e-e2e779d090ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.28.108.46:5337/smile/mod_ld/form/ld5001.php?mid=305010000000000</value>
      <webElementGuid>c37a41ff-f782-499e-a70a-6f1380001454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5624d447-57bc-4873-891c-42187011f304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5e220b3e-739d-4d7b-ac8b-bdac9f919b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ddfdc22e-7998-4f4e-b0aa-025882d49b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>aae0a3f2-a10c-46e8-9f48-bb5558023a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>5779795f-c219-4507-a1ca-1fd024e7180c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)</value>
      <webElementGuid>ceb56fe5-0aae-4f3d-aeee-482e99b99c38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='form']</value>
      <webElementGuid>0d825be0-b4f0-452a-b2db-6a3f0ecd7b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='/mod_ld/form/ld5001.php?mid=305010000000000-innerCt']/iframe</value>
      <webElementGuid>6414569e-81e4-4ff1-908c-25d499492f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6444833f-b00c-4ca9-81b4-36ce7d43cf41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'http://172.28.108.46:5337/smile/mod_ld/form/ld5001.php?mid=305010000000000' and @id = 'form' and @name = 'form']</value>
      <webElementGuid>6d2dd6df-fe66-44c0-9c68-2d4dcd848e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
