<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>eea767d4-0234-4003-b38a-62be8ebbb570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Cari Topik Interaksi Tertinggi&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formKiri']/table/tbody/tr[3]/td/fieldset/div[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ac531297-0981-4e6d-853e-111102ba8f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/help.png</value>
      <webElementGuid>9b2f2748-df4d-4476-9316-4cc55a785768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cari Topik Interaksi Tertinggi</value>
      <webElementGuid>ce48c817-0339-4f83-bf39-610a72f92e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e345f445-88d4-4720-adef-e61c43f74163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>f0830e0b-938c-457d-8eb7-523003b49f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formframe&quot;)/div[@id=&quot;formKiri&quot;]/table[1]/tbody[1]/tr[3]/td[1]/fieldset[1]/div[@class=&quot;form-row_kiri&quot;]/a[1]/img[1]</value>
      <webElementGuid>a8efe9c0-7aee-4e48-aa66-78c734149aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/reset akun dan buka suspend/2 buka suspend/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_LD5001-Perekaman Informasi dan Penga_4f240a</value>
      <webElementGuid>05ae225d-9347-485a-85c1-00244e58b2e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formKiri']/table/tbody/tr[3]/td/fieldset/div[3]/a/img</value>
      <webElementGuid>a0951ea3-32ed-46fe-8032-20bb996905c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cari Topik Interaksi Tertinggi']</value>
      <webElementGuid>dff6cc8e-e343-4a58-b0f1-b523c3273404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>47afd2ac-1306-4978-8934-24aae9ec219c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../images/help.png' and @alt = 'Cari Topik Interaksi Tertinggi']</value>
      <webElementGuid>395161ba-98ca-45a0-af20-166785a21a68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
