<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tb_nomor_identitas</name>
   <tag></tag>
   <elementGuidId>fa603f21-36b1-4751-a56a-609cdb06c1e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tb_nomor_identitas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tb_nomor_identitas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61973600-0837-4e20-9026-d07f2f529d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>042b1bc9-8919-4a6c-8d2b-d9af9f8d950d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>justNumber</value>
      <webElementGuid>ea11755d-b248-4d21-be8c-c24ef1697871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tb_nomor_identitas</value>
      <webElementGuid>3d918c0c-25c1-44e1-9201-cdb40472f994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tb_nomor_identitas</value>
      <webElementGuid>df569c15-08fc-4967-902b-4fde892308d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>e54198d7-c2ef-4d29-84ca-e09727d163ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>getDataNik()</value>
      <webElementGuid>f11a1f30-01de-4b62-b9a5-2b7e6e93a0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tb_nomor_identitas&quot;)</value>
      <webElementGuid>504b8858-8f06-4bea-98cd-afe6b6b394ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/reset akun dan buka suspend/2 buka suspend/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_LD5001-Perekaman Informasi dan Penga_4f240a</value>
      <webElementGuid>c5fde48d-ad5f-4e35-a875-083d2ecfb8cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tb_nomor_identitas']</value>
      <webElementGuid>321dba93-a9dd-48f2-8252-6029808fd3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='dataPelaporPerekaman']/div[2]/input</value>
      <webElementGuid>ab059e84-2c8a-41dd-aa58-0cf0a6d5b1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/fieldset/div[2]/input</value>
      <webElementGuid>075eaaf2-124b-4975-87df-dae4119a75b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tb_nomor_identitas' and @id = 'tb_nomor_identitas']</value>
      <webElementGuid>4512cf5d-42f7-434b-a392-4ed34a2af892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
