<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>418de609-84b9-4681-83ca-681e7cbb1f82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;filter('2', '', '', '', '')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18b1892c-3205-42a0-b7d1-af11be2aedf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6d92b42b-a580-4518-a853-c1159e34cd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Last Page</value>
      <webElementGuid>44062675-0384-4f5e-a805-1b06c724134c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-link</value>
      <webElementGuid>f8469bc7-6a41-4f85-b2bd-cbf0dc9a40d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>filter('2', '', '', '', '')</value>
      <webElementGuid>1ce7ebb0-bfb1-47e3-ab95-11f1797e408d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>>></value>
      <webElementGuid>dcff3a43-f3a5-486e-b363-20723cd04bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formframe&quot;)/div[@class=&quot;div-container&quot;]/div[@class=&quot;div-body&quot;]/div[@class=&quot;div-page&quot;]/div[@class=&quot;div-row-between&quot;]/div[@class=&quot;left-item&quot;]/div[@class=&quot;div-row&quot;]/div[@class=&quot;item&quot;]/a[@class=&quot;icon-link&quot;]</value>
      <webElementGuid>1e022125-d88f-4c42-ba1a-b26894c87e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/validasi-new-edt-delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>3e9859b8-4c33-40bd-a9b1-7f48a2a581ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;filter('2', '', '', '', '')&quot;]</value>
      <webElementGuid>08d8c964-5ec0-44ad-b06b-22e029bb5b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div[3]/div/div/div/div[6]/a</value>
      <webElementGuid>b58c8a7a-41f9-493f-a8e4-b0aeca5b5b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'>>')]</value>
      <webElementGuid>bbbb72ca-6e3f-4a91-a3ad-3bcad321d1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[1]</value>
      <webElementGuid>8fc8eb62-c404-4314-b342-49df445e5b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::a[2]</value>
      <webElementGuid>19d88391-fb55-412f-b0dd-108c4571a853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dari 2 halaman'])[1]/preceding::a[1]</value>
      <webElementGuid>c66725d5-3ecb-4d5b-9eb3-57176580adb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan item ke 1 sampai dengan 10 dari 14 items'])[1]/preceding::a[1]</value>
      <webElementGuid>a5cfeb12-64a7-4bed-a083-e70f694b7e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='>>']/parent::*</value>
      <webElementGuid>bc93e3eb-3963-49c1-a7a8-3dce78d1e1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[10]</value>
      <webElementGuid>6970994b-8488-4c69-9c4e-9249b75ff792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>0fcefb65-7aaf-434a-a6f9-399c37c6cdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'Last Page' and (text() = '>>' or . = '>>')]</value>
      <webElementGuid>70aee5b7-e353-4f83-904d-ded19638a8f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
