<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</name>
   <tag></tag>
   <elementGuidId>19960430-f9df-409f-ae9f-89bc3029e19c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@id='form'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>50630590-c45d-4056-8322-f3120bb8ddd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.28.108.46:5454/smile/mod_ec/form/as1031.php?mid=624310000000000</value>
      <webElementGuid>7b383e7d-8beb-4cee-8b97-f1f0048bc160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c33c6c93-3e49-4d82-866f-82f3f48b7cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>9cac6032-35cb-464e-b9a4-e5f6a7517224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eaabdfdf-690d-4976-8984-d74761e55562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>bc50ea51-bfa8-4f68-9acf-566c22e68bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>1dde5944-5b6b-472e-84d8-60f0a716a434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/mod_ec/form/as1031.php?mid=624310000000000-innerCt&quot;)/iframe[@id=&quot;form&quot;]</value>
      <webElementGuid>427ade74-3ac8-4e69-bf06-ad28bf1ae238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@id='form'])[2]</value>
      <webElementGuid>0909be96-3500-4aa9-9e59-d6b0145226f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='/mod_ec/form/as1031.php?mid=624310000000000-innerCt']/iframe</value>
      <webElementGuid>e89a1c8d-19cc-4afb-ac10-8aa68615b950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/iframe</value>
      <webElementGuid>7b1f46d5-0da9-4679-a6e2-75ea2f0b0d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'http://172.28.108.46:5454/smile/mod_ec/form/as1031.php?mid=624310000000000' and @id = 'form' and @name = 'form']</value>
      <webElementGuid>f12fde79-e140-4582-a86a-cd20dcf69ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
