<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1015202550</name>
   <tag></tag>
   <elementGuidId>e21d949b-8638-47b1-96cb-7ead2c378264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='page_item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#page_item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f20a27fa-270a-4570-9afb-f923ab42f3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>page_item</value>
      <webElementGuid>bb0b4472-9d87-463a-baf4-4db3433cd0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page_item</value>
      <webElementGuid>bbacb8c7-b593-4679-b130-bb4f4b125641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>filter('', '', '', '', '')</value>
      <webElementGuid>0fed7bce-184e-400f-b482-aa9e09521e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									10
									15
									20
									25
									50
									</value>
      <webElementGuid>f6001eaf-4e33-44c6-88f5-528357622f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_item&quot;)</value>
      <webElementGuid>9f4733e5-77e6-4560-ab62-3a494bc6b772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/validasi-new-edt-delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>ef70ebd9-c0b4-4b17-bb96-49b360386c18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='page_item']</value>
      <webElementGuid>c87bbbbb-695d-4675-bde9-0f155b88c298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div[3]/div/div[2]/div/select</value>
      <webElementGuid>c973344f-738b-4e20-818f-0ed36282af28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan item ke 11 sampai dengan 14 dari 14 items'])[1]/following::select[1]</value>
      <webElementGuid>0f9cc3b3-36a4-42d0-9014-2c04e6404f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dari 2 halaman'])[1]/following::select[1]</value>
      <webElementGuid>fac674ad-3f82-446c-a312-a81eabbf5822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan:'])[1]/preceding::select[1]</value>
      <webElementGuid>32b0bcef-4096-497d-a007-306487cf3ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Data Kategori'])[1]/preceding::select[1]</value>
      <webElementGuid>3824eccd-b253-4a7a-b6e2-9dea50d31308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>9e2831e4-de6f-4294-b9fb-e33fb83e81b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'page_item' and @id = 'page_item' and (text() = '
									10
									15
									20
									25
									50
									' or . = '
									10
									15
									20
									25
									50
									')]</value>
      <webElementGuid>bdb7328f-2a08-4835-b15c-5ccd3e5bd2fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
