<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Capture Photo</name>
   <tag></tag>
   <elementGuidId>05658385-e4cf-4489-b286-9b63466e3fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='click-photo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#click-photo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>109bcdaa-755a-4a68-9e63-62a829f6dec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>click-photo</value>
      <webElementGuid>370b988a-1f57-46c3-baaa-05bc3c9bbcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Capture Photo</value>
      <webElementGuid>ef7267fb-8720-4987-b3ec-a89934e3207b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;click-photo&quot;)</value>
      <webElementGuid>fc62849f-59b3-40b5-9550-9499a354e1a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='click-photo']</value>
      <webElementGuid>779f528c-3c0b-44b1-91aa-fe369b171989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Camera'])[1]/following::button[1]</value>
      <webElementGuid>43564bd0-a459-408c-81b3-fc2bd188c135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image Data URL'])[1]/preceding::button[1]</value>
      <webElementGuid>da5c1298-e720-45ab-8522-b6a1859de609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'click-photo', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>37987e5e-0d17-4ddf-8e0d-898783b8af4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Capture Photo']/parent::*</value>
      <webElementGuid>4135c977-a0b0-41c0-9d73-b3bca2b5c871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>19f32b65-22cf-4eae-a567-2b705be5ba4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'click-photo' and (text() = 'Capture Photo' or . = 'Capture Photo')]</value>
      <webElementGuid>9f56b658-ba39-4769-9e3c-9a058d1f043d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
