<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NISN (No Induk Siswa Nasional)_nisn_pelapor</name>
   <tag></tag>
   <elementGuidId>394d1c10-3d88-4a43-a52b-5d2cffd43066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nisn_pelapor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nisn_pelapor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec916a2b-1db9-455c-b4ce-685f3fc48eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nisn_pelapor</value>
      <webElementGuid>cb5febac-db74-48d1-9a81-71cbe6d409c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nisn_pelapor</value>
      <webElementGuid>332d8ac6-782b-40af-b06d-5d319f0d1249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nisn_pelapor&quot;)</value>
      <webElementGuid>931dd0af-65ec-432b-999c-9fbc66f5e817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/manual/NISN/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1014-Perekaman Data Biometrik Pelapor_form</value>
      <webElementGuid>0c235ec7-a272-4077-b78f-5d71578f2d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nisn_pelapor']</value>
      <webElementGuid>d9fc39e7-57be-4216-9968-c7e66b0b7e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetDataPelapor']/div/div/table/tbody/tr/td[2]/div[14]/div/input</value>
      <webElementGuid>6ed89bed-fe5a-4532-aa4a-aa042f91068e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input</value>
      <webElementGuid>a2cb654f-9059-47a9-9348-4cfedcc7e7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nisn_pelapor' and @name = 'nisn_pelapor']</value>
      <webElementGuid>867a6465-8c37-4823-aac1-02c412e4019d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
