<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_nama_kriteria</name>
   <tag></tag>
   <elementGuidId>d71a30aa-24e0-4d65-aff4-8ea7927c1c65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='sc_nama_kriteria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Keyword..&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc6cbbd7-cba3-4096-9548-f92ef24ebaed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf70f1e8-e295-44b7-9c65-af314633511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_txt</value>
      <webElementGuid>be1c3ede-7b26-49c0-826e-30c7adcfe8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_txt</value>
      <webElementGuid>3da77e9f-0c64-43c0-bafd-999fd43a18fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keyword..</value>
      <webElementGuid>11fa0796-c43b-4411-bee8-93202c2480e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_txt&quot;)</value>
      <webElementGuid>e3664b19-c199-4a74-8e77-00893b1537aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Filtering Data/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1023-Filtering Data_form</value>
      <webElementGuid>57d20614-8878-4ed8-8788-24937725f45e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_txt']</value>
      <webElementGuid>5b773b7b-85d5-4156-a108-3f96b6537ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_filter']/div/div/div[3]/input</value>
      <webElementGuid>c777c47d-94bd-44ab-bbde-46135e3569e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a88110d1-56e8-43e2-add6-726414f8932d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_txt' and @id = 'search_txt' and @placeholder = 'Keyword..']</value>
      <webElementGuid>a95716a3-676f-4aeb-b0ce-eff7fb8686cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
