<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>3a261c40-ea63-48a7-8b46-7125c52307d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;filter('-2', '', '', '', '')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.icon-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0d6d986-3ef1-4958-9f37-ce79d032bd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>df79972a-9b88-44ee-9d66-93a5952324d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>First Page</value>
      <webElementGuid>3fc5d5b2-517a-43c0-82dd-1d6f19db0222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-link</value>
      <webElementGuid>6dc919b2-15d5-4fed-a0f1-33352e967139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>filter('-2', '', '', '', '')</value>
      <webElementGuid>daeb0bae-f82b-4018-83bf-8126b2293a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;&lt;</value>
      <webElementGuid>e5f29d8c-6237-4d65-8bc8-6c0320f9b3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formframe&quot;)/div[@class=&quot;div-container&quot;]/div[@class=&quot;div-body&quot;]/div[@class=&quot;div-page&quot;]/div[@class=&quot;div-row-between&quot;]/div[@class=&quot;left-item&quot;]/div[@class=&quot;div-row&quot;]/div[@class=&quot;item&quot;]/a[@class=&quot;icon-link&quot;]</value>
      <webElementGuid>6d323834-01db-4bf1-8ade-b8fa370ef847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/2 sub kategori/4 validasi-new-edit-delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>3e58a13a-aa31-437a-bfe6-ee3276747c92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;filter('-2', '', '', '', '')&quot;]</value>
      <webElementGuid>834af76a-d019-44de-9275-e4493b4eaeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div[3]/div/div/div/div[2]/a</value>
      <webElementGuid>f7870d9e-a1c9-4c3d-b23e-38f44cfcd966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'&lt;&lt;')]</value>
      <webElementGuid>93e3d2d8-4549-4add-82a7-c30e00232c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halaman'])[1]/following::a[1]</value>
      <webElementGuid>dbe0ae5f-0963-4a95-9dcc-38c1a8dce4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKTIF'])[30]/following::a[1]</value>
      <webElementGuid>8a15f079-4492-4856-873a-1a9800b41499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/preceding::a[1]</value>
      <webElementGuid>123098d7-7b7a-412f-89a6-fa1f2b6024a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::a[2]</value>
      <webElementGuid>b2d18908-de84-402f-8f7a-6d2fe4d30b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;&lt;']/parent::*</value>
      <webElementGuid>2d4e7a7a-5b26-4dbf-a40c-34da34b9ae4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[7]</value>
      <webElementGuid>add2c82a-4a24-479c-aa6e-5ccf9ee8859f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>3ca17110-c502-4a6a-aeb3-5ba2bb619eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'First Page' and (text() = '&lt;&lt;' or . = '&lt;&lt;')]</value>
      <webElementGuid>95c4aefa-61bb-472c-8c7e-e103f4f8af80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
