<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_id_subkategori</name>
   <tag></tag>
   <elementGuidId>ec576dbb-77a4-40d9-8c3d-1b218cfe3616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_subkategori']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_subkategori</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49cc9d5f-513a-4b35-91ba-34584f9c1926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_subkategori</value>
      <webElementGuid>c0e880c9-2785-4d87-a222-9b62564dd740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_subkategori[]</value>
      <webElementGuid>57da7011-29f5-4690-9a9a-202ce568ccb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data_ke_1_0</value>
      <webElementGuid>e3c42787-8646-405e-b790-894aa04e57d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.data_ke_1_0').prop('checked', this.checked);$('#checked_all_id_subkategori').prop('checked', false);</value>
      <webElementGuid>d46b714e-04b2-428c-9204-e4889442fe01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eb683f8c-8381-4edd-a5fd-472edfb0a22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FSUB0001</value>
      <webElementGuid>4eb169a4-4cbd-46f8-be8a-6961c10a20cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_subkategori&quot;)</value>
      <webElementGuid>e4b62b1a-5126-49f9-905a-bed84d13f96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/2 sub kategori/4 validasi-new-edit-delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>9f65956c-f11d-419b-b9fd-8a56ab605e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_subkategori']</value>
      <webElementGuid>a51c93bf-68c0-46b9-9f88-dae1ba9f42df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='data_list']/tr/td[2]/input[3]</value>
      <webElementGuid>3affa460-53bb-422f-8fca-f92b8101336b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>ca3c6914-90dd-49d8-ba19-54b9b827932c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_subkategori' and @name = 'id_subkategori[]' and @type = 'checkbox']</value>
      <webElementGuid>f2053b19-027f-47e8-ae3f-8a0f380ed43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
