<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1015202550</name>
   <tag></tag>
   <elementGuidId>b9b08fe3-41da-4312-94cc-85a68fbbd88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='page_item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#page_item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e44ce5de-2193-4510-b134-18ef9bdcee2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>page_item</value>
      <webElementGuid>e2134ebe-92b3-4ed6-910b-63433bbb448c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page_item</value>
      <webElementGuid>e5e14051-05b2-4241-b149-72a0fe21bdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>filter('', '', '', '', '')</value>
      <webElementGuid>574a3976-045e-40cf-823b-5a5532917320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									10
									15
									20
									25
									50
									</value>
      <webElementGuid>584dc95b-035b-4562-a188-eb4a7ce27611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_item&quot;)</value>
      <webElementGuid>8cdb7601-b0f9-44fe-afb4-b63b54706382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/2 sub kategori/4 validasi-new-edit-delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>f3a76529-ff88-43d0-ab92-3370ba82afb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='page_item']</value>
      <webElementGuid>dc4e066f-5cda-497b-bb8d-94f27f8dc239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div[3]/div/div[2]/div/select</value>
      <webElementGuid>8ad577dd-9b5d-49fc-891c-42980d47d5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan item ke 41 sampai dengan 50 dari 60 items'])[1]/following::select[1]</value>
      <webElementGuid>00b2cc52-a95c-44db-a7a6-16387352767d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dari 6 halaman'])[1]/following::select[1]</value>
      <webElementGuid>8c0bf935-39dc-4ac5-aab8-3be23308142d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan:'])[1]/preceding::select[1]</value>
      <webElementGuid>dbbcb839-7699-45fc-b778-2bca7ed764a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Data Kategori'])[1]/preceding::select[1]</value>
      <webElementGuid>c05c826f-7e89-4146-8cab-0c25f257f4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>b1a337f1-f89f-4774-a16c-b341ee870e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'page_item' and @id = 'page_item' and (text() = '
									10
									15
									20
									25
									50
									' or . = '
									10
									15
									20
									25
									50
									')]</value>
      <webElementGuid>a9835193-d412-4389-ada2-2ff23e84d407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
