<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rule</name>
   <tag></tag>
   <elementGuidId>bbaeb1b5-ff7f-4869-9378-79f8831cb03d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combox-inputEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combox-inputEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff2d15c2-b9a4-4b50-be8d-5f00f1c23377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combox-inputEl</value>
      <webElementGuid>dba98897-509a-4259-9e44-feed6cf7d174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df758a0d-0c35-4d2a-b3ff-984107729485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>d8387592-4542-4994-8cb2-d6e8160dd012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>1968fe2b-147a-43a7-9a0b-6ee7bed1b58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f0c9e44e-46b1-4376-91d4-37947731b0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rule</value>
      <webElementGuid>38754b9c-e4cd-44a8-b7bc-a1d0fc8055cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combox-inputEl&quot;)</value>
      <webElementGuid>b04e05e2-ce24-43cd-b109-7243322354cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combox-inputEl']</value>
      <webElementGuid>111994ed-7b41-4527-bd69-0e8599c7803a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='combox-inputCell']/input</value>
      <webElementGuid>721bd564-adba-41dd-829c-cc9acde3bb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dada1e44-3f6d-48ee-a777-d2b16e04a0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combox-inputEl' and @type = 'text' and @name = 'rule']</value>
      <webElementGuid>66baf7b1-65a2-4e01-b84b-2d9b70e78349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
