<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_kategori</name>
   <tag></tag>
   <elementGuidId>e2135132-cda8-4005-a0ef-6a8a7a092e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_kategori</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_kategori']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01af69d8-7cea-4790-bc6d-3fb24c39caad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c238dbd4-652d-4b39-89f1-fd0697f76bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kategori</value>
      <webElementGuid>09fbbc04-3ffe-4c54-9ff5-04a0840bf887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_kategori</value>
      <webElementGuid>c3879160-ab67-43d1-9065-ca1a84d3365a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_kategori&quot;)</value>
      <webElementGuid>f9b92ff8-7142-4b58-9475-1c82c2563488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/EDIT AS1026/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1026- CMS Kategori Tanya 175_form</value>
      <webElementGuid>a6e49193-b186-451d-aa3a-25602867a6aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_kategori']</value>
      <webElementGuid>3e59364d-5a61-4981-844d-30472fc8bd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSubmitCategory']/div[2]/input</value>
      <webElementGuid>c65e28ec-3b24-4303-9c3d-26cd13729ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>83553460-521c-4bfa-9c21-d667eff5b339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_kategori' and @id = 'nama_kategori']</value>
      <webElementGuid>6bedb09b-b050-442f-ae82-5f95333f03b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
