<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih_button-1025-btnIconEl</name>
   <tag></tag>
   <elementGuidId>b05f61d5-600e-4220-821f-7ee3be441013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1025-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1025-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e86543b0-2070-488c-9cb5-34b1b3db0a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>29034487-bc8c-4c79-b32f-1d3045c8aa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1025-btnIconEl</value>
      <webElementGuid>bbb45481-6faf-4218-9cd7-42ad0defc522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>8ad11dcc-8220-4a67-ba2d-53f670a72581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4bf2739d-f357-4951-bf31-5e93ae09b898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1025-btnIconEl&quot;)</value>
      <webElementGuid>a91e9e0b-c4e2-4260-810e-be3445e0edcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1025-btnIconEl']</value>
      <webElementGuid>26478274-5aa9-4861-b65a-300844017fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1025-btnEl']/span[2]</value>
      <webElementGuid>1c1b9c0b-c285-44df-82a3-a7f6af82de37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/span/span/span[2]</value>
      <webElementGuid>db236c78-ad43-4e5e-8914-d74f5b45ff86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1025-btnIconEl']</value>
      <webElementGuid>c3fc6f74-4776-4060-8b95-b2b1c0168722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
