<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__keterangan_kategori</name>
   <tag></tag>
   <elementGuidId>d5ddcbd6-fde8-4fd1-8f05-1657462c395d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keterangan_kategori</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='keterangan_kategori']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1db7515c-7963-4af9-b206-b14b6c022986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keterangan_kategori</value>
      <webElementGuid>0a77a7d3-cfe5-40d3-ad28-993cbae5b56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan_kategori</value>
      <webElementGuid>2944c5d1-359d-48da-9ff4-d139ec11dc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>092837cd-109c-4935-bc99-0eb60a11da39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keterangan_kategori&quot;)</value>
      <webElementGuid>c05ef950-dcaa-45cf-80e2-306a6e6c55d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/EDIT AS1026/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1026- CMS Kategori Tanya 175_form</value>
      <webElementGuid>21c7007e-9f3e-480c-b1bb-af93fef036b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='keterangan_kategori']</value>
      <webElementGuid>6a5506bc-3c45-4888-9ed6-4be96a4568fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSubmitCategory']/div[3]/textarea</value>
      <webElementGuid>70e63daf-3a0e-4dea-bd53-caceb7b1c2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>33254b16-a415-4eae-9598-82ae1823caa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'keterangan_kategori' and @id = 'keterangan_kategori']</value>
      <webElementGuid>8ae99911-69bf-4e17-9ae7-95739ff41a48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
