<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK_button-1005-btnIconEl</name>
   <tag></tag>
   <elementGuidId>5b68097a-52bb-48ca-94c6-8728d3ab386c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1005-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-1005-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb6784a9-41e1-4e93-b17d-1cf7074ff0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7e0c26b5-2dc7-40de-a923-db81c0783415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1005-btnIconEl</value>
      <webElementGuid>d57e7849-8ecb-4ee5-8fda-d5b68bf749ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>63a166c1-3210-4a95-8b81-ebf748aff69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2a617362-af58-49d2-aafb-2c6c55a253bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1005-btnIconEl&quot;)</value>
      <webElementGuid>cf05af81-dafc-4b9f-a330-545f4e644fe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnIconEl']</value>
      <webElementGuid>b5cfc60b-bb68-4be8-86eb-cbbf59a05009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnEl']/span[2]</value>
      <webElementGuid>b349c273-59d7-4635-bcaa-3ada87b426c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/span/span/span[2]</value>
      <webElementGuid>ac861e27-f0db-4fc1-8bc6-e989dfb25c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1005-btnIconEl']</value>
      <webElementGuid>c1150e79-a958-407d-893b-fb7d37a62bf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
