<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rule</name>
   <tag></tag>
   <elementGuidId>a1ad9c8f-68a2-4d37-b64a-b37ca103b2a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combox-inputEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combox-inputEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d06095d-f0f0-4140-bd35-27fe3dc6a495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combox-inputEl</value>
      <webElementGuid>0d479d91-cf9c-4aaa-a054-781955ad46b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>923adc3c-2810-4f51-b783-2aa23ac1fc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5d9da1f6-da9d-4003-96d1-c323322f8c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>2a44a855-2393-47a5-b245-5b13e06e35de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>047513b1-71d4-4ebb-99cf-caf3b1ef3173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rule</value>
      <webElementGuid>7f1dcaef-7635-47fc-87d6-1aea98827725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combox-inputEl&quot;)</value>
      <webElementGuid>51a81b3a-d8a7-4ca0-8083-d5dc06fdfee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combox-inputEl']</value>
      <webElementGuid>0ad65517-09de-465c-81bc-6fd4cdec73be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='combox-inputCell']/input</value>
      <webElementGuid>962538c8-24f3-4686-900b-91b8206d77e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>40d065a0-9d0d-4822-adcc-bfc15622ce62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combox-inputEl' and @type = 'text' and @name = 'rule']</value>
      <webElementGuid>a253d31e-15e2-4b1f-b603-eaa806ef136c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
