<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-- Pilih Sub Kategori --_search_txt3</name>
   <tag></tag>
   <elementGuidId>d7a47c0d-82b6-4501-b4bf-6274c85f2d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_txt3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_txt3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6298972-36c9-4788-aefc-12d1ac70c68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db54b5ac-78a7-4bdf-aee7-f8eb872f2828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_txt3</value>
      <webElementGuid>4320b2b0-49b9-4be5-85c1-a72a15935071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_txt3</value>
      <webElementGuid>e53aa616-7a9c-4220-9acb-77ea470b2814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Kategori</value>
      <webElementGuid>39601d2e-c0ac-4f36-be31-89bf276069cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_txt3&quot;)</value>
      <webElementGuid>d2d2e791-ef6a-4945-95de-25667931c8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/validasi - edit - delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>7f6217ab-73e0-4605-997b-63101831cd21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_txt3']</value>
      <webElementGuid>cbe5c2d6-a641-490d-8cf7-8ed56eb79cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div/div[6]/div[2]/div/div[5]/input</value>
      <webElementGuid>b0125c62-3206-437b-872c-02170c0bd2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>1d18e5e3-ecb5-47ca-be87-754a1b05fc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_txt3' and @id = 'search_txt3' and @placeholder = 'Nama Kategori']</value>
      <webElementGuid>9f465079-9ca7-4787-a75e-2edf37657dd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
