<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UPDATE DATA KATEGORI_btn_simpan</name>
   <tag></tag>
   <elementGuidId>de3d21ff-3b5c-4de5-8614-ad7699e4cbad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_simpan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_simpan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b982dcb-58cb-4e2e-bd36-a9d0b2ad83e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5dcf4a46-4e2e-4867-85e4-85663befb7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn_simpan</value>
      <webElementGuid>381277a0-0a37-455b-82ed-cc7f92feb327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>b782bd5b-a51b-499a-8f91-ed54218cc8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_simpan</value>
      <webElementGuid>6ce99864-cee1-4210-bee3-41ae10275067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>c12129d3-9c3f-49f7-a571-f8dd72b11e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>save('edit')</value>
      <webElementGuid>32404001-4544-413c-9bc4-b5214d3af40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_simpan&quot;)</value>
      <webElementGuid>aef560b7-7b26-4c1c-b9fa-4575afa93d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/validasi - edit - delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>c8c05d94-3382-489b-a641-e8aeeb2926f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_simpan']</value>
      <webElementGuid>a048ea81-1ecd-4713-83f7-3ad1e5a642e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konten']/div/div/div[13]/input</value>
      <webElementGuid>30e7f716-01d5-4f5c-bb66-b41b15911089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/input</value>
      <webElementGuid>6e002698-c55d-4381-8191-bc3f4dc671e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btn_simpan' and @id = 'btn_simpan']</value>
      <webElementGuid>964c976b-71be-412b-996c-c112168e615b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
