<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AKTIF_id_kategori</name>
   <tag></tag>
   <elementGuidId>601fc389-ea75-4669-b915-dc0ef6191895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td:nth-of-type(2) > #id_kategori</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='id_kategori'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9072a429-43a6-4f3d-913d-164e7f2b2c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_kategori</value>
      <webElementGuid>d600deab-3486-4035-95dd-7108c7f0654c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_kategori[]</value>
      <webElementGuid>728caaa5-1369-4423-8c81-b98153e462a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data_ke_2</value>
      <webElementGuid>d1fa1486-e061-42fb-b87f-e2c855e62176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.data_ke_2').prop('checked', this.checked);$('#checked_all_id_kategori').prop('checked', false);</value>
      <webElementGuid>6551cea9-2345-4a99-91d2-eda0d50135b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0fcdc7b1-facb-4b8e-b40e-3803b0353f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FKAT078</value>
      <webElementGuid>a4b64b9e-ecca-4abb-a397-d7cbf10142d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_list&quot;)/tr[3]/td[2]/input[@id=&quot;id_kategori&quot;]</value>
      <webElementGuid>4d4c7513-d5de-4c64-9e93-6d822550d653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/validasi - edit - delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>910078f6-aa2d-49a8-9f10-060777205c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='id_kategori'])[3]</value>
      <webElementGuid>742530ed-e28d-427c-add7-10bfa7c185a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='data_list']/tr[3]/td[2]/input</value>
      <webElementGuid>6d445cb9-b991-436e-8389-5c2f850c0506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>2db0aa6c-6136-4386-9252-abbd7801052a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_kategori' and @name = 'id_kategori[]' and @type = 'checkbox']</value>
      <webElementGuid>32c0a484-9272-434e-960b-35265dc23b76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
