<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KATEGORI_rg_kategori</name>
   <tag></tag>
   <elementGuidId>72be1231-0c02-4319-97a4-40722e5957f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rg_subkategori']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rg_subkategori</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97455e66-76a1-42a2-b6e2-bbe01bcb7499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>48607572-2cf5-422d-9ad9-0976d5efd688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rg_kategori</value>
      <webElementGuid>9ccd2ec2-017c-4d78-8d9b-036d86c90f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rg_subkategori</value>
      <webElementGuid>2525a3c4-99ba-4770-a59b-de60fbfa654e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>a92fc29a-5abe-4847-804f-941d73710a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('select#search_txt').val(null).trigger('change');$('select#search_txt2').val(null).trigger('change');filter('', 'filter', 'Y', '', '')</value>
      <webElementGuid>0314226b-bbde-4589-900c-64f101fffc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rg_subkategori&quot;)</value>
      <webElementGuid>54e7949b-789f-40e3-9ca6-3d833741dd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/2 sub kategori/manual/radio_button_sub/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1031-CMS FAQ Kategori dan Sub Kategori_form</value>
      <webElementGuid>210b9e4e-f5df-406f-b42e-e639074ff59a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rg_subkategori']</value>
      <webElementGuid>f0cf0feb-e4f4-401f-8e00-e3aaa1753ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div/div[6]/div/input[2]</value>
      <webElementGuid>1fe950f1-7bf5-48fd-a8b4-b5cbd1784ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>b9809975-2c25-400e-83e1-0b059910c045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rg_kategori' and @id = 'rg_subkategori']</value>
      <webElementGuid>91cf09ad-eb80-43b2-8156-b8b81b640963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
