<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Aksi_btn_Download</name>
   <tag></tag>
   <elementGuidId>d76de9e9-c8c4-46dd-b76f-cf3ffe92f84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_download']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_download</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;download&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfbcd970-fab1-4bc8-8144-4e1e9a71bbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad44f8b0-fbb4-434b-8c29-04fb9c285ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn_Download</value>
      <webElementGuid>04cc902a-3bfc-4ef1-867b-5c2c79a1393a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>3a38f77a-9f29-4759-82c4-826aeba2b70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_download</value>
      <webElementGuid>2ac43964-1606-4a33-b7e0-f7bfe6c5213a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>download</value>
      <webElementGuid>a5a9b58b-3da8-40b0-9470-b2aef82b09a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>download()</value>
      <webElementGuid>325d5eca-e70a-4901-a608-9c6ad31cd8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_download&quot;)</value>
      <webElementGuid>c4076722-d8d2-44f8-92ae-a48d4f53bf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Promo/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1027-Upload Data Blasting Promo_form</value>
      <webElementGuid>51e48a75-87ba-44a1-a97d-89e7e81eef83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_download']</value>
      <webElementGuid>1bdfa39c-9302-47b6-894c-dfeae812951e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konten']/div/div/div/div/fieldset/div[4]/div[12]/input</value>
      <webElementGuid>01226e35-329d-4c3c-b0a7-c7a38c1d6861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[12]/input</value>
      <webElementGuid>1d8581f3-9aae-4131-a4eb-a133f21f9568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btn_Download' and @id = 'btn_download']</value>
      <webElementGuid>6d2638a5-5c8b-44f6-812f-d46cb4e9af7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
