<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_id_subkategori</name>
   <tag></tag>
   <elementGuidId>05925a2e-de6f-44e6-8e84-977d5ca48c0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_subkategori</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_subkategori']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>181efedd-ed91-4060-8c0e-89898d75f63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_subkategori</value>
      <webElementGuid>8cdbcba4-f4fc-47f0-9999-64619257f465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_subkategori[]</value>
      <webElementGuid>8b4583d6-2bc3-46a9-a513-5d392e385660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data_ke_1_0</value>
      <webElementGuid>a41a2dd4-a0fd-488b-9078-91a4f9b8540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.data_ke_1_0').prop('checked', this.checked);$('#checked_all_id_subkategori').prop('checked', false);</value>
      <webElementGuid>f9953515-51de-4a34-9e38-fb88c0f37602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1fee6c67-2f4b-4579-b166-c2ab38522440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FSUB0003</value>
      <webElementGuid>4c0dc486-8a0e-4d46-80cb-82a530a583f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_list&quot;)/tr[@class=&quot;tr_page tr_page_1&quot;]/td[2]/input[@id=&quot;id_subkategori&quot;]</value>
      <webElementGuid>6955c317-edfa-485f-8776-6434e631394d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/sub kategori fix/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>28f7ece8-5b97-403e-9b92-36216073b1d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_subkategori']</value>
      <webElementGuid>f9fd7468-7ada-412d-9307-951928716120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='data_list']/tr/td[2]/input[3]</value>
      <webElementGuid>3cbfdc6f-0c48-462a-9d81-dcc281befd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>36f699cd-4cf9-4d12-a633-17f844d082c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_subkategori' and @name = 'id_subkategori[]' and @type = 'checkbox']</value>
      <webElementGuid>e3817953-77ac-4b47-a6b4-25d60d59b75a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
