<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KATEGORI_rg_kategori</name>
   <tag></tag>
   <elementGuidId>075e55df-5242-4e52-a8c2-e8a2cdaa60ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rg_subkategori</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rg_subkategori']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>573e01d9-c891-4d64-aa3a-2ebb9580affd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>768f9165-e7b4-4744-8195-0262e16c7ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rg_kategori</value>
      <webElementGuid>70770812-fcb8-4d85-ade9-cbcac2adc01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rg_subkategori</value>
      <webElementGuid>b8309498-dc40-4503-a92d-b9d4a53b61c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>147b9d3e-aab9-4480-a5a7-fdc0d8f2fd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('select#search_txt').val(null).trigger('change');$('select#search_txt2').val(null).trigger('change');filter('', 'filter', 'Y', '', '')</value>
      <webElementGuid>3caea812-5337-410f-b1bb-5ac802d0b14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rg_subkategori&quot;)</value>
      <webElementGuid>f60860f4-0bf5-47a9-abe5-c4ca5e179d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/sub kategori fix/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>d62816de-6b7b-4e91-a6eb-1e5b9db8381a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rg_subkategori']</value>
      <webElementGuid>e47328cf-6eac-4a49-a289-10dbd47b8851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div/div[6]/div/input[2]</value>
      <webElementGuid>bfaaf58f-8a6a-4ed8-8ebb-45f60480cc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>77eb546f-a2c9-42a9-a610-036d69c7a45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rg_kategori' and @id = 'rg_subkategori']</value>
      <webElementGuid>c0e4d744-45f4-4268-b6b9-10739862f0e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
