<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TAMBAH DATA SUB KATEGORI_btn_tutup</name>
   <tag></tag>
   <elementGuidId>6f4c5aa2-cbaa-4c35-aa08-1dfbef64f82c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_tutup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_tutup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c059b824-9810-4322-9e7e-07f4b34d71df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5bc11ee-eff2-4371-b19d-2bf65fdfe1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn_tutup</value>
      <webElementGuid>ec7fa791-084a-4885-bc78-ecf4656d0121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>aa062c7f-3884-4d2b-b470-f29d979ce2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_tutup</value>
      <webElementGuid>ed054b60-2294-4620-afbf-c56f1b8f0641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tutup</value>
      <webElementGuid>646e87f5-7cf8-427d-acfe-319c4db05491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>kembali()</value>
      <webElementGuid>101f7e0f-60ab-44ea-bcc2-7df90060e8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_tutup&quot;)</value>
      <webElementGuid>a575b4de-7694-4193-a58e-814664275862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/sub kategori fix/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>1d3405c3-fe47-4c0b-8cba-5ee85d697cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_tutup']</value>
      <webElementGuid>ec8280b9-2e0c-4113-bb14-51924b3b96e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konten']/div/div/div[13]/input[2]</value>
      <webElementGuid>bfcfd711-0cb1-4de4-b6a3-692303478665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>291e963d-0b0b-4a15-b7a3-02f9b5c91ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btn_tutup' and @id = 'btn_tutup']</value>
      <webElementGuid>3fc4c959-0eca-43aa-99e9-e060a3272ab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
