<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih Sub Kategori --</name>
   <tag></tag>
   <elementGuidId>527b9e52-620a-4742-8483-3d0f63bedab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-search_txt2-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-search_txt2-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>881dc56e-8df9-4811-aaac-a10d3c68d46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>6b3368b4-3255-46c5-9254-c5bacae57c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-search_txt2-container</value>
      <webElementGuid>47282f13-e8c2-451a-8c2a-58111b1cb08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>17b575bf-102d-4382-97d1-c1d6e1de5773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>235f1c70-e18d-4c7b-b316-a7c212fe4198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih Sub Kategori --</value>
      <webElementGuid>1b8ffed5-8442-46bd-8b36-b69740523f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×-- Pilih Sub Kategori --</value>
      <webElementGuid>d93afb34-0982-4f52-9e25-1b0daaeeb98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-search_txt2-container&quot;)</value>
      <webElementGuid>1f42a953-678e-43ae-b14b-4de7b7c4ce7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/sub kategori fix/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>dd298fda-2fd7-48d4-ad72-5df7f31c80ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-search_txt2-container']</value>
      <webElementGuid>23a59780-9731-468d-8e7d-0e6a0957f5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div/div[6]/div[2]/div/div[4]/span/span/span/span</value>
      <webElementGuid>037ac26d-058d-4c6d-9a5e-247582056157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Kategori:'])[1]/following::span[4]</value>
      <webElementGuid>69ddc143-a65a-426e-9108-26050cad2a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Pilih Kategori --'])[2]/following::span[6]</value>
      <webElementGuid>1a1d5594-c9fd-4e26-b134-6382843656e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::span[4]</value>
      <webElementGuid>b6cf54ea-01e1-4b88-8638-c349512cb913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/span/span/span</value>
      <webElementGuid>7f4211a6-538f-4daa-83e6-c81cd8be8c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-search_txt2-container' and @title = '-- Pilih Sub Kategori --' and (text() = '×-- Pilih Sub Kategori --' or . = '×-- Pilih Sub Kategori --')]</value>
      <webElementGuid>30de56e0-8574-43bc-a513-e244cddc86cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
