<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login_button-1016-btnIconEl</name>
   <tag></tag>
   <elementGuidId>f6721d09-06ac-4892-9506-7c3dc3549b3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1016-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1016-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f0d78947-3b40-4fe0-b693-aed4ccea9a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>50db3f95-cfa0-403f-9094-de4ea2665e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1016-btnIconEl</value>
      <webElementGuid>64f93720-b5ab-4b59-a432-8cfaeaa658f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>4c65ca08-bd6d-48ea-b777-9c068b223bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f9d3b281-4801-4119-a1b2-0660fe171f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1016-btnIconEl&quot;)</value>
      <webElementGuid>76f86881-9369-4435-9989-47db2b73c8d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1016-btnIconEl']</value>
      <webElementGuid>21699bac-da59-4f71-834f-9dc0987c0bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1016-btnEl']/span[2]</value>
      <webElementGuid>2577aac7-2da2-4602-9e3e-d5cf2a693c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span/span/span[2]</value>
      <webElementGuid>e795ffb8-f9a7-4a88-b22c-9fe704cfc7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1016-btnIconEl']</value>
      <webElementGuid>fb8f2305-4c80-41bc-b964-cdfa8809a3af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
