<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AS1014-Perekaman Data Biometrik Pela_4e1763</name>
   <tag></tag>
   <elementGuidId>2fa34d30-4e45-4215-85e9-85eb507bc5e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='form']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;form&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4b68e7b3-d461-4750-b863-750dd174c0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.28.108.46:5332/smile/mod_ec/form/as1014.php?mid=624140000000000</value>
      <webElementGuid>f730312c-4bd5-44fc-b43f-49dd2cf7e651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>745a6781-0f4b-4996-8337-45aca3718786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d11685bf-1546-4649-9693-e890c68d3077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51ab0bed-106a-43b2-9f0e-c289b248b99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>fbb180cc-9533-47c1-ac51-1cfaf35a4d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>766ecd5f-ebcf-4d8d-831a-c56f3eeff978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)</value>
      <webElementGuid>9b53ac59-6c60-4899-a80a-688ffbea6671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='form']</value>
      <webElementGuid>38a9c6b9-3309-4645-bcce-84343f5224a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='/mod_ec/form/as1014.php?mid=624140000000000-innerCt']/iframe</value>
      <webElementGuid>e76b2191-6105-46ed-9679-bcbba0a17d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e5fe4b2f-4207-41f1-a05d-ca42e1366122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'http://172.28.108.46:5332/smile/mod_ec/form/as1014.php?mid=624140000000000' and @id = 'form' and @name = 'form']</value>
      <webElementGuid>d84836d5-6ff5-46fc-a113-d6e14a514cbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
