<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_id_subkategori</name>
   <tag></tag>
   <elementGuidId>1247e4f3-2a06-4bef-9472-ad36ed9721d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_subkategori']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_subkategori</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f3474f2-1c35-4324-a58c-7782e1803e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_subkategori</value>
      <webElementGuid>48161663-acd0-411c-9d8a-573d189c1757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_subkategori[]</value>
      <webElementGuid>547e80c8-ebe2-4795-baad-e56ffb64cf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data_ke_1_0</value>
      <webElementGuid>76749ee0-7a36-4c61-8e60-622965934d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.data_ke_1_0').prop('checked', this.checked);$('#checked_all_id_subkategori').prop('checked', false);</value>
      <webElementGuid>1bff611b-8fed-4ba1-ad1f-e5f2a0e13fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c6bc4e44-0311-41ef-9b96-5d3eb3036de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FSUB0002</value>
      <webElementGuid>4c904aa8-8e6c-4f3e-8b4c-cae3d0ca2cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_subkategori&quot;)</value>
      <webElementGuid>fe20d7a1-c444-4b4c-b1d9-2c35dc904c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/2 sub kategori/validasi-new-edit-delete/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>e18cd575-ebfa-46c1-9a30-b0e48d71e810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_subkategori']</value>
      <webElementGuid>641c411f-2fbc-4b2f-8c93-980cc6db29d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='data_list']/tr/td[2]/input[3]</value>
      <webElementGuid>5d59d8f6-0efb-4593-a99b-b2850119ba72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>04ce37f9-ebfe-4cfd-a474-306f90bc2572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id_subkategori' and @name = 'id_subkategori[]' and @type = 'checkbox']</value>
      <webElementGuid>9859e95b-a2ac-4384-b9c9-3dbd55d6e524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
