<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tanngal_edit</name>
   <tag></tag>
   <elementGuidId>db9bb948-1ee9-47fc-a8f6-cf67136e1458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSelectSchedule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSelectSchedule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;2024-09-07&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a3ecc7a-7597-458f-a872-7cf17fc7f6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-select-schedule</value>
      <webElementGuid>d3783d80-d79d-4e44-a82d-25e156019c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSelectSchedule</value>
      <webElementGuid>130d52cb-1140-4b3e-a314-1cdb2399cb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9206ed01-0a24-4add-83c0-9aa89e41b856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2024-09-07</value>
      <webElementGuid>f7f00953-de33-42f1-8e3d-e30788dcab0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSelectSchedule&quot;)</value>
      <webElementGuid>4eba46fe-291b-44ff-8e32-02a31463cecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Campaign/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1024-BlastingCampaign_form (1)</value>
      <webElementGuid>fcf2f04a-3c07-4c2c-8a0b-b9d49e4f8bc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSelectSchedule']</value>
      <webElementGuid>efb394ce-30a1-487e-9c8c-7968213ceabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formWrapper']/button</value>
      <webElementGuid>f6248329-ed6e-4a0e-a3fa-dcb9d8aab101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim kepada peserta memiliki Akun JMO Valid'])[1]/following::button[1]</value>
      <webElementGuid>85cff991-7a3a-491c-8385-75b1de6c8552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjadwalan / Scheduling'])[1]/following::button[1]</value>
      <webElementGuid>66cf3f40-2a90-4288-88cb-f23c46e146c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One time notification'])[1]/preceding::button[1]</value>
      <webElementGuid>67324ef8-debf-4fa9-8bd6-96b6d55ac74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sekarang'])[1]/preceding::button[1]</value>
      <webElementGuid>e5bbf5ab-ea93-41fe-b58b-7cf671af84cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2024-09-07']/parent::*</value>
      <webElementGuid>c04d6be5-93dd-4a72-9196-3bc5aff5be3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/button</value>
      <webElementGuid>693e0812-5398-466d-9c61-69c5c79ed324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSelectSchedule' and @type = 'button' and (text() = '2024-09-07' or . = '2024-09-07')]</value>
      <webElementGuid>6efca3d8-b596-4232-8ab8-2bc795bcc22a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
