<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sekarang</name>
   <tag></tag>
   <elementGuidId>50ae9824-de0a-48de-b6b2-1e80c01bc9d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSelectSchedule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSelectSchedule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Sekarang&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b2aa538-de2f-4980-af89-f31bf700a9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-select-schedule</value>
      <webElementGuid>295800bb-b153-4381-9e5e-5d7dd0b9a8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSelectSchedule</value>
      <webElementGuid>1a2ee234-9a3a-4277-a7aa-ce1391098907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed72cab0-9b2d-4970-bc8b-2a0388a5a192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Sekarang
                                            </value>
      <webElementGuid>9700a67e-31a6-42ce-9fa9-5caab746e122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSelectSchedule&quot;)</value>
      <webElementGuid>bcbb0a03-c3ed-4a18-af13-f8121cc8bc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Campaign/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1023-Filtering Data_form</value>
      <webElementGuid>58521fce-092a-42f7-9c8b-07325ab084fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSelectSchedule']</value>
      <webElementGuid>22fe0555-9e9e-411a-99bf-dca1e2ac3209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formWrapper']/button</value>
      <webElementGuid>fbefd574-eae9-41b8-89df-93ba1bce0967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim kepada peserta memiliki Akun JMO Valid'])[1]/following::button[1]</value>
      <webElementGuid>a168c811-dfc1-49ff-bae0-deba61dc462b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penjadwalan / Scheduling'])[1]/following::button[1]</value>
      <webElementGuid>4e8949f6-8e93-4529-b443-2a4d3ae311c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One time notification'])[1]/preceding::button[1]</value>
      <webElementGuid>9909664e-fb07-4dd7-8242-8837653633f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sekarang'])[2]/preceding::button[1]</value>
      <webElementGuid>2cf9ca52-e15a-413f-8e38-e177b337d5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sekarang']/parent::*</value>
      <webElementGuid>192fa8e1-cc11-4251-9815-5f92af5879cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/button</value>
      <webElementGuid>4c8cde74-9554-4ee9-a0db-52d3e8ddf932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSelectSchedule' and @type = 'button' and (text() = '
                                                Sekarang
                                            ' or . = '
                                                Sekarang
                                            ')]</value>
      <webElementGuid>77d1b11d-c9be-40ba-9d04-e43dcc9ccfcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
