<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AS1024-BlastingCampaign_form (2)</name>
   <tag></tag>
   <elementGuidId>96c56049-23dd-45bf-94b0-24a59bea02a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@id='form'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;form&quot;] >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fe87d71b-af35-4e0b-8224-8560f5ca50aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.28.108.46:5331/smile/mod_ec/form/as1024.php?mid=624240000000000</value>
      <webElementGuid>a3300691-c1e5-4130-bde7-8e7c6a8db781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>87763781-116d-4813-a8ea-9fc3a4f06fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b45629f6-41fe-4abd-b535-cf715e1ec21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>820281fb-f8da-4a6e-8d21-3e9b866f4c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>5d78ceb0-f3c5-4ece-8156-370675b930c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>ceb6a926-8d9a-464c-9183-903902d6eb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/mod_ec/form/as1024.php?mid=624240000000000-innerCt&quot;)/iframe[@id=&quot;form&quot;]</value>
      <webElementGuid>4f9297bd-954a-4d70-b158-b75cb4592ed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@id='form'])[3]</value>
      <webElementGuid>5956cfb4-68e0-4b63-9f4d-04d8d82efc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='/mod_ec/form/as1024.php?mid=624240000000000-innerCt']/iframe</value>
      <webElementGuid>c31ebc57-429e-4e75-8716-41e81e38522e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/div/iframe</value>
      <webElementGuid>5453bad5-a99c-48b1-8a11-a065620ef939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'http://172.28.108.46:5331/smile/mod_ec/form/as1024.php?mid=624240000000000' and @id = 'form' and @name = 'form']</value>
      <webElementGuid>4d888304-8c04-44f2-a4c0-5d197a7a9239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
