<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_and_trash-icon</name>
   <tag></tag>
   <elementGuidId>0316fa26-40a1-4504-b82c-c2a344808663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.trash-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selectWrapper2']/button[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;trash-icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b88797e1-def1-4cb2-84f6-e3ff18abade7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../assets/icon/trash-svgrepo-com.svg</value>
      <webElementGuid>128aadd4-25d6-49bb-b09c-82f15b829284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>trash-icon</value>
      <webElementGuid>36f37201-fbe1-4b67-82b9-a68c32eb4733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trash-icon</value>
      <webElementGuid>748813d0-3691-4b2d-93d5-ff6ea2b4acbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectWrapper2&quot;)/button[@class=&quot;removeSelectButton&quot;]/img[@class=&quot;trash-icon&quot;]</value>
      <webElementGuid>96c5c8b3-03b3-475d-be8d-6c23c230849a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Campaign/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1024-BlastingCampaign_form</value>
      <webElementGuid>fa5c3b08-1857-43c1-9722-03a4af8e1c01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectWrapper2']/button[2]/img</value>
      <webElementGuid>affc1fba-fb18-4c86-aaa6-618f2a5d6bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='trash-icon']</value>
      <webElementGuid>177c7fb8-4a1b-4439-9bce-b7de7c8d69a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>c601516b-5e32-424b-a1eb-7953f13c821d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../assets/icon/trash-svgrepo-com.svg' and @alt = 'trash-icon']</value>
      <webElementGuid>167a3e17-91fd-439b-8057-d5e424028783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
