<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kirim kepada peserta memiliki Akun JMO Valid_scheduledTime</name>
   <tag></tag>
   <elementGuidId>08b9dd7e-2ddb-46ff-b934-ead5cb3b41fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scheduledTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='scheduledTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#scheduledTime</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a904c152-28f6-4e1b-8597-bdf5e60fc2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>71bea288-ff5d-474b-a912-b2a9fef3a4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ml-2</value>
      <webElementGuid>d727851b-60f7-4135-b646-13b900b61670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scheduledTime</value>
      <webElementGuid>c15a778b-ed08-4a21-b5af-2f7e3068aec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scheduledTime</value>
      <webElementGuid>d3b1fff2-558d-430b-b556-7458ab8d1050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>08:00</value>
      <webElementGuid>a4d9b6ff-5977-4af4-afda-373f622f3346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scheduledTime&quot;)</value>
      <webElementGuid>673be6fa-9aa0-4846-b362-84f5c840196b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Campaign/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1023-Filtering Data_form</value>
      <webElementGuid>dc7d6f70-49a0-4fb1-b9a5-4a4be48d8108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='scheduledTime']</value>
      <webElementGuid>ef1a570d-1482-4f96-a203-a988691aa3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scheduleForm']/input</value>
      <webElementGuid>b19909bd-5d1f-40e6-86e9-b11e3ec31049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>a835f8b6-f119-4e6b-9a43-4285cde6e180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @name = 'scheduledTime' and @id = 'scheduledTime']</value>
      <webElementGuid>8e302ff8-559e-4fe5-bc2a-52a847ee380d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
