<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tanggal_dipenjadwalan</name>
   <tag></tag>
   <elementGuidId>0218f985-6ac5-4de0-97a1-cc80eb585afe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optionCalendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btnSelectSchedule&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#optionCalendar</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b052c0f-853e-4d70-8523-cd7818314754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d7575bf1-c028-44ed-bea2-94cd2688e1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8a4c9818-e2aa-4f43-8ad3-edfccd4843e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optionCalendar</value>
      <webElementGuid>232d01e2-9d55-44c3-adea-400aa13aff06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optionCalendar</value>
      <webElementGuid>24d23256-5d78-4fa9-8c93-656fa9a167d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2024-09-06</value>
      <webElementGuid>5ab2a992-fdd2-4653-bfad-50ba3c2a7def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optionCalendar&quot;)</value>
      <webElementGuid>1e0e711e-85a6-423a-a4d2-0d4fc0fad011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Campaign/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1023-Filtering Data_form</value>
      <webElementGuid>2956c951-636d-46ea-a9f4-1fb00110fc68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='optionCalendar']</value>
      <webElementGuid>2cfff5e7-114b-45cf-be6a-d03f1fb4f57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optionScheduledCalendar']/input</value>
      <webElementGuid>3250ed73-dedd-4293-9017-e8f33bc68a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d7821f9a-df49-4cec-88c0-f9156c3b3e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'optionCalendar' and @id = 'optionCalendar']</value>
      <webElementGuid>0cf18722-cf95-43fb-8ad2-5cf6323f0870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
