<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>keyword</name>
   <tag></tag>
   <elementGuidId>cc72e707-4190-418b-828b-d6eac50b5464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-dynamicSelect1-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;keyword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;-- Pilih kriteria --&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c09afaa5-72bd-4642-9584-77fc178c2784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>177d547a-4550-414e-9c2e-e78c1199b96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-dynamicSelect1-container</value>
      <webElementGuid>ab7de4e3-b56d-479f-a6fc-b5dc3b5055f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2a383b04-5c12-459c-a4c9-f73ad2ac9841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48e04700-4dec-448a-8976-29964b8ed772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih kriteria --</value>
      <webElementGuid>7f980bd8-a00c-4dd2-b11f-38ae866632b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih kriteria --</value>
      <webElementGuid>274d8a07-8c85-43f6-81ea-7b55cc5a054b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-dynamicSelect1-container&quot;)</value>
      <webElementGuid>6393bd12-2694-44fc-b28a-d3b6492c8b2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-dynamicSelect1-container']</value>
      <webElementGuid>957bcfc5-bce3-4722-9b12-04d1252db119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectWrapper1']/span/span/span/span</value>
      <webElementGuid>a4e87aaa-5bc2-4352-bf28-2e7a24db0e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kriteria'])[1]/following::span[4]</value>
      <webElementGuid>1fb9b539-913d-45f7-8a06-d23af7b32c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target kriteria pengguna JMO'])[1]/following::span[4]</value>
      <webElementGuid>93ec536d-0afd-45ed-a385-915b8a3ff06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='and'])[1]/preceding::span[3]</value>
      <webElementGuid>c3d6123a-adc2-48e5-9aa9-7a210b371711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/preceding::span[3]</value>
      <webElementGuid>31c8c82e-e35d-487e-b28b-72e3d8559fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>3bae50aa-803a-4e83-b274-d6ac0373f7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-dynamicSelect1-container' and @title = '-- Pilih kriteria --' and (text() = '-- Pilih kriteria --' or . = '-- Pilih kriteria --')]</value>
      <webElementGuid>54fc60a4-7980-42c6-befc-f23eddcaa49b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
