<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_by</name>
   <tag></tag>
   <elementGuidId>bcad5fa3-9b43-4090-a969-8be33519f6cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-dynamicSelect1-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;type&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;-- Pilih kriteria --&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c8dba6f-14f4-49d8-b720-1301d089fd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f6b9b41e-3fb7-493a-8056-b632d1c2e2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-dynamicSelect1-container</value>
      <webElementGuid>8504eb4f-1187-40a4-946a-a64743b784ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ceffd552-87f5-4669-8f38-2343c278a427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7facd0f2-c8e5-4c72-814c-0bdb5e4fe58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih kriteria --</value>
      <webElementGuid>3a2ac977-7281-46fb-ba08-3fdaaccceb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih kriteria --</value>
      <webElementGuid>1cd8cf20-fc48-4463-8efa-be1a182f0cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-dynamicSelect1-container&quot;)</value>
      <webElementGuid>b1c06dca-12f2-43f2-8d5a-2c82fafec3b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-dynamicSelect1-container']</value>
      <webElementGuid>8834d208-af10-47f7-be8d-501d6f93b5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectWrapper1']/span/span/span/span</value>
      <webElementGuid>5dfe451d-3486-4a25-826d-819bc5cde502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kriteria'])[1]/following::span[4]</value>
      <webElementGuid>85a26cd0-5ed5-4c99-8e58-18aed257e9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target kriteria pengguna JMO'])[1]/following::span[4]</value>
      <webElementGuid>3d86e76a-2e4c-4091-ae1b-280c5d4a6337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='and'])[1]/preceding::span[3]</value>
      <webElementGuid>896e6eea-bcc3-4672-ab39-69c795b6e16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/preceding::span[3]</value>
      <webElementGuid>578e6f09-68e8-47bd-87ef-2f68485c474c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>bb725d42-c063-40c2-b492-74e19687319e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-dynamicSelect1-container' and @title = '-- Pilih kriteria --' and (text() = '-- Pilih kriteria --' or . = '-- Pilih kriteria --')]</value>
      <webElementGuid>1ce101c4-a247-45ec-996b-72be9d9a40c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
