<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>730a5eb9-688b-48ac-88c5-c1b5fde1459e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5) > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;editCategory('T068')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8fe782d-5e89-499b-927a-33698d71563a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e1ffad20-87e6-4b58-8e3e-a1179a1f0af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>editCategory('T068')</value>
      <webElementGuid>4d5cd0c0-596e-430b-ac2e-c181cad95fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>822e3e67-aa3c-40c8-af5a-2a8256c7f48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tableDataKategori&quot;)/tr[@class=&quot;odd&quot;]/td[5]/div[1]/a[1]</value>
      <webElementGuid>b3afa0d4-f4be-4321-9493-437155802856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/edit sukses dan validasi/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1026- CMS Kategori Tanya 175_form</value>
      <webElementGuid>75e92d2c-767f-4600-8d82-9a5162eda5b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;editCategory('T068')&quot;]</value>
      <webElementGuid>c265404c-51ac-426e-9031-458dae71047c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tableDataKategori']/tr/td[5]/div/a</value>
      <webElementGuid>d47c041f-e402-4b78-a6d0-8009f6a4a14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>3b2fada4-045a-4817-986b-50bae130ab70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[1]/following::a[1]</value>
      <webElementGuid>6cc3d12e-86ab-49c9-819e-d38a496fb7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIDEO DAN DOK65'])[1]/following::a[1]</value>
      <webElementGuid>00883691-dd9a-4b59-8960-11ee3b381654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 62 total entries)'])[1]/preceding::a[1]</value>
      <webElementGuid>88dd5baf-1ba3-4b7f-be23-d99f649ba720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First'])[1]/preceding::a[1]</value>
      <webElementGuid>f874d9a8-033f-45b8-828c-41c92f662d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>210b4891-87ce-4d14-817c-a76b8730971c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>034c60bf-3555-478d-898c-a265138bcc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/a</value>
      <webElementGuid>14623b44-ac8a-407c-aa36-e5cc14ab29f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>8476c63a-a7d6-4137-aea0-4ba5b47d7d85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
