<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AS1026- CMS Kategori Tanya 175_form</name>
   <tag></tag>
   <elementGuidId>59dd083a-76b9-4911-9619-89cd7ecfe0ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@id='form'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>081cd28c-8f13-4284-af54-accc41274e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.28.108.46:5444/smile/mod_ec/form/as1026.php?mid=624260000000000</value>
      <webElementGuid>f447d112-76c2-423f-a193-b39f3a67f078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>bc82b3b4-697d-48d6-9a13-772014f37202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8f79b294-1b29-40c7-a841-f1e5b3822090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fd247e56-69b4-4f81-aa9b-56957da8a04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>e6168498-71a6-471a-b180-c054d3d1fb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>62c47871-b3ca-4816-8820-bcab7bf73aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/mod_ec/form/as1026.php?mid=624260000000000-innerCt&quot;)/iframe[@id=&quot;form&quot;]</value>
      <webElementGuid>32e17ef4-fd72-4b9f-b96b-dffb3b2db6f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@id='form'])[2]</value>
      <webElementGuid>ccaf528b-b3eb-4a8c-b45b-dc64d3c4fd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='/mod_ec/form/as1026.php?mid=624260000000000-innerCt']/iframe</value>
      <webElementGuid>18874754-b243-46a3-ac3d-72a220d62498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/iframe</value>
      <webElementGuid>5a112361-d09d-4af3-8f77-b89932fc13ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'http://172.28.108.46:5444/smile/mod_ec/form/as1026.php?mid=624260000000000' and @id = 'form' and @name = 'form']</value>
      <webElementGuid>2449588f-06fe-4a3a-8559-b53b1f7d240c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
