<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_kategori</name>
   <tag></tag>
   <elementGuidId>0d0f398f-3cf2-4a9b-875a-a0542e832f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_kategori</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_kategori']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20abf84e-89e8-48d9-8cea-e467cde5f256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a82829c9-333c-447d-8e2d-5c49a4541eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kategori</value>
      <webElementGuid>2ef7fa17-8972-410f-9122-101b701ee7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_kategori</value>
      <webElementGuid>e49f22b7-0df9-494a-af67-d31f4fbc323e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_kategori&quot;)</value>
      <webElementGuid>6464d468-6d0e-48ee-992d-5293f93d835a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/edit sukses dan validasi/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1026- CMS Kategori Tanya 175_form</value>
      <webElementGuid>3986d929-15a8-4106-908f-58e8127465aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_kategori']</value>
      <webElementGuid>11f95371-5fc8-45cf-b7f1-340ab4f72d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSubmitCategory']/div[2]/input</value>
      <webElementGuid>ce0ec31b-563f-4200-ab96-adf15c1536be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1f382758-5d5b-40a6-bf7b-07f3c3820803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_kategori' and @id = 'nama_kategori']</value>
      <webElementGuid>2a799287-0221-45c9-8660-32c188238db9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
