<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1015202550</name>
   <tag></tag>
   <elementGuidId>15a0c0c4-603f-4d68-88dc-15480b37515b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#page_item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='page_item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c90c71f-a585-4556-b65c-18b8723aca2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>page_item</value>
      <webElementGuid>df6d3f83-1a93-43e2-8ef7-57cdb304d187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page_item</value>
      <webElementGuid>f1c3c4f1-b892-4ad2-8ff3-e472dd97f490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>filter('', '', '', '', '')</value>
      <webElementGuid>7d00da86-ffc6-4f8c-9937-98c4e032b82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									10
									15
									20
									25
									50
									</value>
      <webElementGuid>6144db3a-dc0f-4cea-abed-dfa454f72572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_item&quot;)</value>
      <webElementGuid>b5927bff-04fe-4559-825b-10a6ea6cae43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/kategori-new-edit-delete-validasi/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>8952f4b6-b10e-4b18-9fb5-03696dd2cc20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='page_item']</value>
      <webElementGuid>8f703b4f-16c5-4f1b-b323-194e855fadeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div[3]/div/div[2]/div/select</value>
      <webElementGuid>f1a2a3e1-8cb1-4b4a-8501-36a240d67f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan item ke 1 sampai dengan 10 dari 29 items'])[1]/following::select[1]</value>
      <webElementGuid>5497cc16-8296-417a-b306-e594751cad5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dari 3 halaman'])[1]/following::select[1]</value>
      <webElementGuid>cf51eea7-e77b-4aa7-a931-fe64dbaeba42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan:'])[1]/preceding::select[1]</value>
      <webElementGuid>8629e4ae-61be-41ab-a7c9-7d8c2e13c358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Data Kategori'])[1]/preceding::select[1]</value>
      <webElementGuid>f1a4656d-f267-4b99-9439-64c364d0edb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>b9749b4d-c5d2-4af2-b963-1e9613f50854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'page_item' and @id = 'page_item' and (text() = '
									10
									15
									20
									25
									50
									' or . = '
									10
									15
									20
									25
									50
									')]</value>
      <webElementGuid>1f37e9d4-bed2-4020-9bb0-8c510f98e71f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
