<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_btn_aktifasi_email</name>
   <tag></tag>
   <elementGuidId>6c45c0ca-1278-4651-ae88-655558a704bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_aktifasi_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_aktifasi_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9138c52-163a-4f8b-99ea-e1858c55c8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27cb01eb-f40b-41bd-943a-9ea4b867f7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn_aktifasi_email</value>
      <webElementGuid>59765bd2-4df8-4981-977e-ed1f5eae7ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>db309b66-9f3b-477a-b3db-fa64fd693b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_aktifasi_email</value>
      <webElementGuid>d2160b91-5898-44cd-b002-81aaa254cf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>37495b89-0fa4-4e70-811d-8dc5733b6377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>kirimAktifasiEmail()</value>
      <webElementGuid>5ba68a63-c2bf-4fa4-9f15-d901270dca46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_aktifasi_email&quot;)</value>
      <webElementGuid>3b7c9d0e-fc8c-402e-801b-4f31c132100b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1014-Perekaman Data Biometrik Pela_4e1763</value>
      <webElementGuid>c08dd303-1cd3-4399-8041-15f6e44fe3d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_aktifasi_email']</value>
      <webElementGuid>b189c2e5-59d5-4019-96d7-06bf1dfff5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='dataAkunJMO']/div/div/table/tbody/tr/td/input[3]</value>
      <webElementGuid>c7949f9f-56a1-4228-aa0e-67b619f8ef80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td/input[3]</value>
      <webElementGuid>577b6f3c-770f-4e7c-9794-9bac8836e7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btn_aktifasi_email' and @id = 'btn_aktifasi_email']</value>
      <webElementGuid>215e6ed4-c6a2-4b3c-bc14-b882efc43953</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
