<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NISN Tidak Ditemukan_btn_simpan_pelapor</name>
   <tag></tag>
   <elementGuidId>192dc0ce-396f-4bc1-b761-6a3fd79c9aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_simpan_pelapor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_simpan_pelapor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e3958a0-7d39-48ff-8d56-6c8eef4c486e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8cdb8eb6-dc72-441d-9d92-825d6f9bffc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn_simpan_pelapor</value>
      <webElementGuid>5edc8a18-5304-4196-82ba-f7a061b072fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>63417e85-5910-4a51-93b2-9f8d2940f4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_simpan_pelapor</value>
      <webElementGuid>b6700f53-1b81-40b2-ab6e-28ede231526c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SUBMIT</value>
      <webElementGuid>d201362c-39db-4d61-863c-7f4a49bda0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitDataPelapor()</value>
      <webElementGuid>a805c37e-4e73-4f34-987d-68563566af78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_simpan_pelapor&quot;)</value>
      <webElementGuid>0a23ebde-bd24-4778-97b5-8e9b691d3b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1014-Perekaman Data Biometrik Pela_4e1763</value>
      <webElementGuid>3cf222c3-7014-40cd-8aab-c7bbb1618b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_simpan_pelapor']</value>
      <webElementGuid>32e2eed9-7222-4d19-91bf-2286d6ebc931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetDataPelapor']/div/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>e0800081-7d8d-4c5f-8855-086e1735c833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>dc55d70f-18d1-45a7-8eb3-efcb1a1212b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btn_simpan_pelapor' and @id = 'btn_simpan_pelapor']</value>
      <webElementGuid>8d2b4d92-ed44-4f6c-9e80-ac373ba10903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
