<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ibu Kandung_ibu_kandung_pelapor</name>
   <tag></tag>
   <elementGuidId>1e376b20-ccfb-4d60-b7d2-219db914217e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ibu_kandung_pelapor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ibu_kandung_pelapor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf3a00fc-e178-4301-91c6-d9c199597df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ibu_kandung_pelapor</value>
      <webElementGuid>f3a35fea-6d43-43d5-8345-a42a58ef238c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ibu_kandung_pelapor</value>
      <webElementGuid>6f7cf4fe-8f93-4756-8d55-97e0d651bc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value = this.value.toUpperCase();</value>
      <webElementGuid>9d84e7ea-a976-40c9-8fba-0d2a318112cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ibu_kandung_pelapor&quot;)</value>
      <webElementGuid>aba27fca-1cde-47b9-a099-4f66efc5c709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1014-Perekaman Data Biometrik Pela_4e1763</value>
      <webElementGuid>b931b8c1-c730-40ec-a2fe-4e4e7b1b9efe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ibu_kandung_pelapor']</value>
      <webElementGuid>4583152b-7a52-4aba-94cb-684264377afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetDataPelapor']/div/div/table/tbody/tr/td/div[12]/input</value>
      <webElementGuid>aa282cc4-cc6f-460f-a54b-d8fee74b5e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/table/tbody/tr/td/div[12]/input</value>
      <webElementGuid>e25d5575-0b07-473a-bc2f-0d1058f80fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ibu_kandung_pelapor' and @name = 'ibu_kandung_pelapor']</value>
      <webElementGuid>d590826b-ddfe-4370-9af0-e9b3b204218b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
