<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih Golongan Darah--AABBO</name>
   <tag></tag>
   <elementGuidId>32d3a58d-ffd7-4c86-bc1f-2ac2499b5e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='golongan_darah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#golongan_darah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>455ac705-8e37-4d36-897f-240fc00082a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6356e7fe-5970-4a57-9284-cbb94b053c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>golongan_darah</value>
      <webElementGuid>02fc8afb-ab83-4887-8963-463853a08ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>golongan_darah</value>
      <webElementGuid>44c37414-026a-43a5-a8c0-90e018bc8659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Golongan Darah--AABBO</value>
      <webElementGuid>8baf37c2-e7d7-4892-bb2a-3a0b3e9139c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;golongan_darah&quot;)</value>
      <webElementGuid>8781d349-eaec-4c05-b0d8-925b79d828dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1014-Perekaman Data Biometrik Pela_4e1763</value>
      <webElementGuid>be863639-58b1-47e5-9e64-ccf5feaa77dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='golongan_darah']</value>
      <webElementGuid>3949a522-bf66-4faa-a0b9-d1a650d33296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetDataPelapor']/div/div/table/tbody/tr/td/div[20]/select</value>
      <webElementGuid>510455a1-a3a6-4683-a707-2a0fa58aac80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Golongan Darah'])[1]/following::select[1]</value>
      <webElementGuid>72abbfec-8ba6-40d1-8fda-efc521896abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perempuan'])[1]/following::select[1]</value>
      <webElementGuid>6e7b85fd-851d-4c4c-a52e-5c1476173cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Domisili'])[1]/preceding::select[1]</value>
      <webElementGuid>a3b3d981-af4e-488c-baa4-23a7520076f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Pos'])[1]/preceding::select[1]</value>
      <webElementGuid>649dcc80-d94f-4e79-a077-48f0120a2219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/select</value>
      <webElementGuid>6b07c9e0-842f-4a85-8193-dc1136d79b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'golongan_darah' and @name = 'golongan_darah' and (text() = '-- Pilih Golongan Darah--AABBO' or . = '-- Pilih Golongan Darah--AABBO')]</value>
      <webElementGuid>5ffe2cc8-357f-48a4-842d-f0e1e52eb9bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
