<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih Status Hubungan--PENERIMA B_6d0f48</name>
   <tag></tag>
   <elementGuidId>22736f46-c4fe-4934-888b-654991308cbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='nama_hubungan_pelapor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nama_hubungan_pelapor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ac149cf-2d04-4990-bb17-f1f42786b4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7c50bba9-9876-4806-a902-1e8aeff7147e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_hubungan_pelapor</value>
      <webElementGuid>9f95139c-7797-43b0-9114-40a185bfd03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_hubungan_pelapor</value>
      <webElementGuid>1819e313-8e3f-439d-ab95-ace30fdac635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cekHubungan()</value>
      <webElementGuid>bdbf9c10-6df1-49ab-b4a6-bb6988f25040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Status Hubungan--PENERIMA BEASISWA IPENERIMA BEASISWA II</value>
      <webElementGuid>a4756db7-2694-4f9c-9674-c727db627723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_hubungan_pelapor&quot;)</value>
      <webElementGuid>b3ea2603-7dbf-42a2-a62b-983e87ec0af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1014-Perekaman Data Biometrik Pela_4e1763</value>
      <webElementGuid>02af0581-ab7b-4465-a917-306f734225a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='nama_hubungan_pelapor']</value>
      <webElementGuid>32377cc5-6c57-4298-bad4-3afe5d7a6fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetDataPelapor']/div/div/table/tbody/tr/td/div[4]/select</value>
      <webElementGuid>75e6452c-8b41-459c-b791-5b49669dcec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungan dengan pekerja'])[1]/following::select[1]</value>
      <webElementGuid>0e0c3a20-b63f-4d62-967a-e34b5cbd39e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Penerima Manfaat'])[1]/following::select[2]</value>
      <webElementGuid>9cc15929-0a1f-40ce-98f7-f5f575171050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Hubungan Lainnya'])[1]/preceding::select[1]</value>
      <webElementGuid>920ab523-4664-4ead-be94-ad4aa1b008a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Penerima Manfaat'])[1]/preceding::select[1]</value>
      <webElementGuid>249ae986-e8d2-4bce-b342-968c85c996b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>e6701360-89b0-47e2-b490-7082eab3f49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'nama_hubungan_pelapor' and @name = 'nama_hubungan_pelapor' and (text() = '-- Pilih Status Hubungan--PENERIMA BEASISWA IPENERIMA BEASISWA II' or . = '-- Pilih Status Hubungan--PENERIMA BEASISWA IPENERIMA BEASISWA II')]</value>
      <webElementGuid>4994fb75-7f13-42ae-92f7-4e496a9cc8a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
