<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih_button-1025-btnIconEl</name>
   <tag></tag>
   <elementGuidId>3c955f6e-da1e-43fb-b24d-26742ca7edfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1025-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-1025-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd6b8c46-3336-4866-bf2b-4a67809755a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>60d1a643-a833-4d6c-ae98-576aac258d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1025-btnIconEl</value>
      <webElementGuid>4e3ce94a-f173-400a-a7ec-7df3e9be93e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>ecfac470-6284-4348-a0b3-38f6916dfd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a47f9452-8f5f-4d96-a6c5-ac97eaaf205e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1025-btnIconEl&quot;)</value>
      <webElementGuid>0669e9f8-f79a-47d0-9ed2-0c284808f427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1025-btnIconEl']</value>
      <webElementGuid>a713c22b-7c18-48be-89f4-aafbe4d66d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1025-btnEl']/span[2]</value>
      <webElementGuid>5ece9db6-5a2b-4044-9ce4-fde265c69dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/span/span/span[2]</value>
      <webElementGuid>af2e2b38-aafb-436b-b30a-a413df265b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1025-btnIconEl']</value>
      <webElementGuid>43202beb-edf0-4ba9-8b31-8f059c6a16d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
