<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes_button-1006-btnIconEl</name>
   <tag></tag>
   <elementGuidId>0c3d76c0-d609-407f-b60e-e0ff14fc9e81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1006-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-1006-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>88503dd7-06d2-401d-93da-9acc6a15054d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>4e272f7d-3cc1-4729-9e01-42d79e306268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1006-btnIconEl</value>
      <webElementGuid>2be62d0b-3e02-4a9f-8f8d-194f7adc9232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>b559af7b-3787-4d8f-895e-0e13c251e648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d2062e40-9ee0-4c3c-b4ec-20ff91651e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1006-btnIconEl&quot;)</value>
      <webElementGuid>fc683e23-663a-4cbd-bbca-cf9d8a0ef4d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1006-btnIconEl']</value>
      <webElementGuid>8e0d507c-2d20-4d96-aeaa-eb3664a642d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1006-btnEl']/span[2]</value>
      <webElementGuid>eb26d632-f766-403c-a9fd-d846d6c1849d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a[2]/span/span/span[2]</value>
      <webElementGuid>0ffade4b-92d5-4167-ba20-c82d1a7b1caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1006-btnIconEl']</value>
      <webElementGuid>ea95b1ec-5203-4fec-9395-1e620dedb330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
