<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keterangan hasil verifikasi_ketera_896fd6</name>
   <tag></tag>
   <elementGuidId>1987f7fc-5282-4f12-abe3-d16099cbbb37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='keteranganWawancara']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#keteranganWawancara</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7b9cf25b-2f2a-4590-9f8b-2442b35b0983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keteranganWawancara</value>
      <webElementGuid>a771d41e-8569-4b9c-879a-efc69b5693c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keteranganWawancara</value>
      <webElementGuid>2fd2a72a-ce87-4cb1-bc7c-1b4b502e1d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keteranganWawancara&quot;)</value>
      <webElementGuid>d2a9cdf5-f4ea-466a-879f-ed60b02bafbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1014-Perekaman Data Biometrik Pela_4e1763</value>
      <webElementGuid>f76e486d-b8f3-45ee-bb1b-3a3c6d41feed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='keteranganWawancara']</value>
      <webElementGuid>9375aa11-c0e3-40ab-afb9-6ca62ad9c8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='dataTindakLanjut']/div/div/div[2]/textarea</value>
      <webElementGuid>da19e4fb-a736-486a-bbcd-07b71e40b6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/textarea</value>
      <webElementGuid>152c3b78-5348-463a-8447-5f85693941c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'keteranganWawancara' and @name = 'keteranganWawancara']</value>
      <webElementGuid>97cd78fb-e156-43ab-863c-707e919d3d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
