<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_tampilkan_data</name>
   <tag></tag>
   <elementGuidId>5881c0e7-86e2-4502-b762-5b0d049fb567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnfilter4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btnfilter&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f1bd822-fc0b-49e3-8ab7-76bf1d5c9b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9781f125-0c27-4659-b2f5-f04cbe6e893a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnfilter4</value>
      <webElementGuid>876d717e-c582-4fdc-a4a1-3c81d26b58a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>1dc9a956-627d-42ca-bd0e-05f49401eea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnfilter4</value>
      <webElementGuid>c317541f-42d8-41bf-9664-7dd9345a44db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>b735e07c-e825-4837-b27d-999b0d90973e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>uploadTK()</value>
      <webElementGuid>25ce847a-2694-44de-b75b-7cd73be9cbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnfilter4&quot;)</value>
      <webElementGuid>0e72a65b-e212-4e64-ad73-09907eb12d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Filtering Data/Filtering Data/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1023-Filtering Data_form</value>
      <webElementGuid>10c7bd86-1fb5-42f9-9a33-d17d110d435a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnfilter4']</value>
      <webElementGuid>660e99b9-1ca1-4865-9d7d-abbc4033cbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_body']/div[2]/input</value>
      <webElementGuid>cf1caa21-cee6-4b9f-b278-2f4196f79235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>55b12c1a-5686-4118-b8e6-cb999c92da8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnfilter4' and @id = 'btnfilter4']</value>
      <webElementGuid>c82f9ccf-03f1-4b45-936f-cc802c02af46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
