<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnsubmit</name>
   <tag></tag>
   <elementGuidId>913723ad-a735-46f4-b78d-c3d3a3e6252a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnsubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnsubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SIMPAN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>912c7088-9727-411c-9eaa-064508b53fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a32964d-c5e6-432e-8823-f911a6115889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>9ddf9664-b79e-4454-ad7d-ac3c2413a72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsubmit</value>
      <webElementGuid>ebc5720c-05c4-4f0b-b81d-00267ef2d2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnsubmit</value>
      <webElementGuid>a90e8c5e-9ea5-4f98-992c-18bfb5906fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SIMPAN</value>
      <webElementGuid>8bcc3f58-a38f-4c09-ac0b-2ab35c92ca53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onSimpanClicked()</value>
      <webElementGuid>bef62b2b-550f-4d55-b468-ef149e0e82a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsubmit&quot;)</value>
      <webElementGuid>591d6840-4c7b-47ce-979a-99dbd5cfdd51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnsubmit']</value>
      <webElementGuid>70597819-cdc3-4e93-942d-d98b621576b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buttonbox']/table/tbody/tr/td/input[3]</value>
      <webElementGuid>b002e522-4061-4ff8-bf6a-1abffec8e516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td/input[3]</value>
      <webElementGuid>dce872e1-1e8d-42bd-a35c-5bef60299df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnsubmit' and @name = 'btnsubmit']</value>
      <webElementGuid>3319f9c2-72b0-46c0-8a1d-650398e53a1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
