<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__ext-gen1096</name>
   <tag></tag>
   <elementGuidId>8069886d-590b-4950-a8bf-84f4011e3180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ext-gen1096</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ext-gen1096']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ext-gen1096</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>053698e2-141d-49f4-a37a-ea13def768a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-trigger-index-0 x-form-trigger x-form-arrow-trigger x-form-trigger-first x-form-trigger-over x-form-arrow-trigger-over</value>
      <webElementGuid>f05481c4-320b-40c7-a0db-9fe141791f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>f1ba694f-e831-4b2b-b8c9-8098f7d04627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-gen1096</value>
      <webElementGuid>9f16b341-b309-474c-abfc-20999baa2684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen1096&quot;)</value>
      <webElementGuid>27461734-9fb2-49b2-829f-9cbbdcae3a92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ext-gen1096']</value>
      <webElementGuid>9599ff17-7535-48fe-92d0-ee8e694629ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ext-gen1097']/div</value>
      <webElementGuid>293ba816-aeba-48ea-9bce-3f537b624771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/div</value>
      <webElementGuid>8a479d6a-3b33-4d41-9d1a-5a70e2dbd83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ext-gen1096']</value>
      <webElementGuid>47596387-2e80-4865-9285-73958f66469f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
