<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JMO_btndownload</name>
   <tag></tag>
   <elementGuidId>4e541381-ce0f-40a9-b17d-c7c91cd0d63f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='btnupload'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;DOWNLOAD TEMPLATE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e9b7ccc-9fda-4049-ab2f-42e8635cf473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a3f7ebf-2500-44c1-9d11-096b476d50d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>dcb4e9c4-2732-4079-a5f5-33a67cb61bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnupload</value>
      <webElementGuid>b00ccb6a-86b7-44db-bb34-02232856be2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnupload</value>
      <webElementGuid>7b0fbf39-48e2-4312-89c2-9cf30c95e7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DOWNLOAD TEMPLATE</value>
      <webElementGuid>f9c3b562-5395-4468-9877-fc62420c3ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>downloadTemplate();</value>
      <webElementGuid>b3634e77-d06f-415e-b8c5-41a5ea28869f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-popup&quot;)/table[@class=&quot;caption&quot;]/tbody[1]/tr[1]/td[1]/input[@id=&quot;btnupload&quot;]</value>
      <webElementGuid>a5f27b4b-0458-42b5-ba22-e69fd740ec4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='btnupload'])[2]</value>
      <webElementGuid>a8229050-9a8e-4ca4-990c-d222bae4d8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-popup']/table/tbody/tr/td/input[3]</value>
      <webElementGuid>5058b1dc-8555-4faa-919e-fbc4278cbac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>517d6a80-6573-4f1d-a109-c007d6ad5754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnupload' and @name = 'btnupload']</value>
      <webElementGuid>102221f1-ac70-4617-8565-f65fe6cfbdb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
