<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_by</name>
   <tag></tag>
   <elementGuidId>2c021ebd-158c-4b83-b9c9-690feb736c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namaKriteria</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='search_by']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namaKriteria</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>46545235-093d-4ff9-88d3-4234ccc7a795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0849d75f-be39-40c0-b451-c2c912958ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namaKriteria</value>
      <webElementGuid>a89d23d4-653c-406d-afe0-a1cab30bdb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namaKriteria</value>
      <webElementGuid>7afcf647-c964-4b0a-abf3-9b3cb32ceeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>37a475fd-da5b-463c-8d08-1005d0c7d61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namaKriteria&quot;)</value>
      <webElementGuid>ffc1f551-c5d4-47df-b01f-f8f5aac71714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='namaKriteria']</value>
      <webElementGuid>04aead65-ab32-4d1f-95fd-ca046f13d20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data_entry']/div/table/tbody/tr/td/div/textarea</value>
      <webElementGuid>21495e20-74ee-4136-8ee5-1e941a6d86d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2fba194e-3f14-4ac0-be80-0b4297c089e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'namaKriteria' and @name = 'namaKriteria']</value>
      <webElementGuid>4e727afd-41e5-4b9c-a7fc-15c6ecccf2a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
