<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_by_nama_kriteria</name>
   <tag></tag>
   <elementGuidId>5ae9f18f-30f7-42e9-bf4d-7c84c33811b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#namaKriteria</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;search_by&quot;]/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#namaKriteria</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a1f819e9-edc0-40e7-a14a-82b1cce54eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df6f9e4d-2f0f-484d-99c7-780d808bf227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namaKriteria</value>
      <webElementGuid>83af502e-4531-4390-b605-164f450d8bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namaKriteria</value>
      <webElementGuid>4ea38250-d00b-41cf-8a32-8ea6c2d399c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>1925a7b7-13a3-4f0f-bfda-c60ef9b090e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namaKriteria&quot;)</value>
      <webElementGuid>e8ff02d4-8333-4e4e-bd97-055b1490942e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='namaKriteria']</value>
      <webElementGuid>7a55c243-dc79-4ff4-ba95-cc10c7a53bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data_entry']/div/table/tbody/tr/td/div/textarea</value>
      <webElementGuid>e70fbe9a-0658-47c4-bd86-ef6bc9d60204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c020f976-ed31-41f5-89cd-a672d19579ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'namaKriteria' and @name = 'namaKriteria']</value>
      <webElementGuid>76335157-ceef-45d7-b47c-5aaf04543fec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
