<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih_button-1025-btnIconEl</name>
   <tag></tag>
   <elementGuidId>d9b570be-25aa-4822-8877-c314c541c6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1025-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1025-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#button-1025</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f399296-9126-4510-9e2b-5801def895f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>5290b73c-c413-494f-b0bc-907c2448f5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1025-btnIconEl</value>
      <webElementGuid>3eecfa46-d413-430e-87a1-d810257edc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>d423bbda-f3f5-490d-971e-7f59088db5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7091e885-18ae-43ce-905a-f2d02e407112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1025-btnIconEl&quot;)</value>
      <webElementGuid>401a0ee3-f93a-4056-8fe0-f7fb8bb06dbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1025-btnIconEl']</value>
      <webElementGuid>8c5086ed-11a5-4ea3-9203-3b459cb1fe8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1025-btnEl']/span[2]</value>
      <webElementGuid>0576cd13-4ee5-48cb-befc-a7d9b4b2f58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/span/span/span[2]</value>
      <webElementGuid>a05178ce-b984-40d5-9ab4-318d0b5d828b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1025-btnIconEl']</value>
      <webElementGuid>a54f351c-1120-4bb6-b29a-3d0694569ed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
