<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fileUpload</name>
   <tag></tag>
   <elementGuidId>2c47094c-9780-41a6-a42e-98fd6573a8be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fileUpload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fileUpload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#fileUpload</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7131e47a-6f53-47b5-acbe-351d60643e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e89fce03-2778-48c6-8687-b8863dc61c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fileUpload</value>
      <webElementGuid>44feffbb-6986-4fe1-bdaf-60145787f0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileUpload</value>
      <webElementGuid>57cca541-06de-4e30-8ade-18f1c23ac0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>text/csv</value>
      <webElementGuid>790130c6-2535-4bca-a7cf-7783af4533dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileUpload&quot;)</value>
      <webElementGuid>45610fcd-51ee-4081-9212-38136263d398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Promo/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1027-Upload Data Blasting Promo_form</value>
      <webElementGuid>148b93eb-a4b3-4e78-97eb-9033b2269311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fileUpload']</value>
      <webElementGuid>fc7567f5-78ac-4874-87fe-1a575f066298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konten']/div/div/div/div/fieldset/div[4]/div[2]/input</value>
      <webElementGuid>fde82052-02a9-4bbc-9ec4-f8dbdb4dc78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>349bc585-7c86-45fe-a7ae-63ebec34d47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'fileUpload' and @id = 'fileUpload']</value>
      <webElementGuid>081577e6-a026-4fbc-a83b-48c4f7f71eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
