<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Notifikasi</name>
   <tag></tag>
   <elementGuidId>8e589bfd-3f29-42a4-8adf-e36995d9d0a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-dark.stepper__header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formNotificationWrapper']/div/div/div/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Notifikasi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ffe09dc0-4e23-44be-8f0d-b011bc7e290e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-dark stepper__header</value>
      <webElementGuid>d36af57a-92c0-4c68-94a9-6b22b72b97ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notifikasi</value>
      <webElementGuid>1f9958d9-c3b6-45fd-b7a7-6ed76a2107a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formNotificationWrapper&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;stepper d-flex flex-column mt-5 ml-2 w-100&quot;]/div[@class=&quot;d-flex mb-1&quot;]/div[@class=&quot;mb-4 w-100&quot;]/p[@class=&quot;text-dark stepper__header&quot;]</value>
      <webElementGuid>d6be23c4-2aec-41f2-a68e-32393af49caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Campaign/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1024-BlastingCampaign_form</value>
      <webElementGuid>9bb00a18-8ba0-45bd-8713-381bf0aa6902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formNotificationWrapper']/div/div/div/div/div[2]/p</value>
      <webElementGuid>f61146f3-d278-4cc8-ba72-a2a6f9a03549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AS1024 - BLASTING/CAMPAIGN'])[1]/following::p[1]</value>
      <webElementGuid>ed1502c4-99f5-4a11-a26b-2121fb792be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification title'])[1]/preceding::p[1]</value>
      <webElementGuid>41a8f305-f39a-42c8-a634-e0ccac695481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification text'])[1]/preceding::p[1]</value>
      <webElementGuid>56df5c91-f529-472e-9425-53b181ef4c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notifikasi']/parent::*</value>
      <webElementGuid>271be754-73b5-4b42-93ef-b7bdc7b93533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>d4304d9a-7fb1-4a6f-a902-a28ec48bc795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Notifikasi' or . = 'Notifikasi')]</value>
      <webElementGuid>9ba1f3a2-ff27-4d24-85a9-2c1de2339676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
