<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK_button-1005-btnIconEl</name>
   <tag></tag>
   <elementGuidId>c203eb4a-14a0-469e-92ea-6b14cce819b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1005-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1005-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2649c6bc-8f65-4915-9c3d-807f9e970b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>3e9733f4-1f05-48b1-a390-b7b7f273bac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1005-btnIconEl</value>
      <webElementGuid>c0a22a22-112a-49de-9367-db7c79fb5581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>b5e963a5-6b67-4e30-afea-8b228f20e916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>68a3beff-a590-441d-a9b1-415de9e615ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1005-btnIconEl&quot;)</value>
      <webElementGuid>cd4b03be-286f-45a5-b58c-7bd5ff971376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnIconEl']</value>
      <webElementGuid>e5eba0f6-d07b-4f73-b498-5125e1036cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnEl']/span[2]</value>
      <webElementGuid>aa92e289-0eae-40fd-8913-c5adb48e5caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/span/span/span[2]</value>
      <webElementGuid>d0223ef8-5a41-41f6-b089-16e7c10802a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1005-btnIconEl']</value>
      <webElementGuid>3d351326-4ac3-41d5-abba-e67d70b6cb8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
