<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__keterangan</name>
   <tag></tag>
   <elementGuidId>d522f6d2-0210-4a56-95ee-83b58853e886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keterangan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='keterangan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8b1d9cb7-8719-4514-8958-b5b9453a37f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7722dd38-c999-4da4-8b68-5758f4eb1bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>5de63533-afd1-4879-9512-6b72b107868d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>8b19d187-a856-4792-8a94-b66d2d558cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>637f2cc5-4573-481d-aac8-f64886c43530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keterangan&quot;)</value>
      <webElementGuid>8a25b1e5-5c61-4cf4-947c-fd201c65311e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/edit konten/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1017- CMS Tanya 175_form</value>
      <webElementGuid>b6f76e2d-4226-4ec4-a9cf-f8fb7e66f921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='keterangan']</value>
      <webElementGuid>36122a4f-5f6b-47ff-93eb-a7c69ddf1ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='video_wrapper']/div[5]/textarea</value>
      <webElementGuid>c30a4e41-90e1-4b94-b77c-caab38152484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/textarea</value>
      <webElementGuid>2b329794-bcb8-4d7f-bc1a-eba0e9865a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'keterangan' and @name = 'keterangan']</value>
      <webElementGuid>257fa4b7-0a8c-442c-b6c1-65e444d638e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
