<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Ibu Kandung_flag_disclaimer_reset</name>
   <tag></tag>
   <elementGuidId>979dcc7d-3bc1-4400-9ec2-0cd4926f5244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flag_disclaimer_reset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flag_disclaimer_reset</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9faf05b-fa5a-4b13-92d1-abce701a697f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4a52e81a-3bf9-4915-9b96-9c6e1d73f14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flag_disclaimer_reset</value>
      <webElementGuid>3ad58426-75db-4bb0-a2a0-f8e5ec279a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flag_disclaimer_reset</value>
      <webElementGuid>9086f814-7fe4-4344-a38c-690a1a08a303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flag_disclaimer_reset&quot;)</value>
      <webElementGuid>de2a5c31-ad21-4066-86a9-3f6fc5ee72df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/reset akun dan buka suspend/1 reset akun/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_LD5001-Perekaman Informasi dan Penga_4f240a</value>
      <webElementGuid>0512aec4-6408-4b37-ae9b-acf30341b0a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flag_disclaimer_reset']</value>
      <webElementGuid>6c89b77a-e808-4876-842f-639c009c9f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_flag_disclaimer_reset']/input</value>
      <webElementGuid>1233f7c9-08e3-4636-ad19-3df3698a0746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[17]/input</value>
      <webElementGuid>5faf49a7-f3bc-47f6-bb79-98512ff4d686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'flag_disclaimer_reset' and @name = 'flag_disclaimer_reset']</value>
      <webElementGuid>67658322-dee4-4f2b-8623-743ebbd5689b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
