<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih Status Pengajuan --Kantor P_9e48f2</name>
   <tag></tag>
   <elementGuidId>035e81c9-4b4c-47d3-825e-b1ec5a6031e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lov_sumber_informasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lov_sumber_informasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1b4a3f20-39af-48ba-bdd8-45d0e594f60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>836f0523-a78f-4d4f-acc2-312a75131b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lov_sumber_informasi</value>
      <webElementGuid>8827a806-ac51-4385-899f-50979d09e2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lov_sumber_informasi</value>
      <webElementGuid>179cc61c-2e59-46e5-a0f0-c9d1da371437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>480e7067-30ec-42fd-94a4-5eb44c6d7d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_format</value>
      <webElementGuid>adfeb141-1d43-45e0-9f0a-0ca259e95f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Status Pengajuan --Kantor PusatKantor CabangKantor WilayahHalo JKPRekomendasi Pihak KetigaPortal LaporCare CenterContact CenterMedia SosialDokumen SuratPesan Singkat</value>
      <webElementGuid>b48a6efb-b85d-4134-aa70-93d56dfd37cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lov_sumber_informasi&quot;)</value>
      <webElementGuid>d7682f97-7ce2-45c9-bad2-8bb7ae7e666e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/reset akun dan buka suspend/1 reset akun/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_LD5001-Perekaman Informasi dan Penga_4f240a</value>
      <webElementGuid>5badf803-4b3f-4a37-8f2c-8f3a3f3d520c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lov_sumber_informasi']</value>
      <webElementGuid>acea2702-5f01-4ca0-b8aa-6118d33c11f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formKiri']/table/tbody/tr[3]/td/fieldset/div[13]/select</value>
      <webElementGuid>d5442f6e-a482-4fca-a84e-71bf71606cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sumber Aktivitas'])[1]/following::select[1]</value>
      <webElementGuid>e867086f-5b30-4036-81dd-4a7fdf005a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Penanganan'])[1]/following::select[1]</value>
      <webElementGuid>8005a11f-5121-40cd-a18a-2d07f5b008dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Selesai'])[1]/preceding::select[1]</value>
      <webElementGuid>5961be3e-67ad-4221-aa8a-ec2892aace4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>162e2274-fc13-4ade-a26e-ccc177831fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'lov_sumber_informasi' and @name = 'lov_sumber_informasi' and (text() = '-- Pilih Status Pengajuan --Kantor PusatKantor CabangKantor WilayahHalo JKPRekomendasi Pihak KetigaPortal LaporCare CenterContact CenterMedia SosialDokumen SuratPesan Singkat' or . = '-- Pilih Status Pengajuan --Kantor PusatKantor CabangKantor WilayahHalo JKPRekomendasi Pihak KetigaPortal LaporCare CenterContact CenterMedia SosialDokumen SuratPesan Singkat')]</value>
      <webElementGuid>a5c28158-849d-4039-97cf-fcf42de45d66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
