<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UsernamePasswordThis field is required</name>
   <tag></tag>
   <elementGuidId>dabeaa6d-826f-4dc1-8655-554e69232743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#encryptionloginform-1010-innerCt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='encryptionloginform-1010-innerCt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7c2c8e8-0c59-49d8-8614-7976bdc8d523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>encryptionloginform-1010-innerCt</value>
      <webElementGuid>5355cb78-975a-4573-b81b-917de9ae0951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>f185fb68-5103-4d83-9972-57589a6c15dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username:Password:This field is required</value>
      <webElementGuid>416bf084-8a1e-4c9d-99b4-b258ff8f8327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;encryptionloginform-1010-innerCt&quot;)</value>
      <webElementGuid>f8464f01-c651-4bee-a993-b2d15cf4fd1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='encryptionloginform-1010-innerCt']</value>
      <webElementGuid>ea1ccb77-ad0b-4798-8cca-66d086c0b68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='encryptionloginform-1010-outerCt']/div</value>
      <webElementGuid>8e636247-7e8f-413c-a9e5-431574fa9398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login SMILE System'])[1]/following::div[5]</value>
      <webElementGuid>3de58aa3-e723-4041-8f47-9cd7d193f418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span/div</value>
      <webElementGuid>b0946b9f-b39b-46fb-86ed-754a396fedf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'encryptionloginform-1010-innerCt' and (text() = 'Username:Password:This field is required' or . = 'Username:Password:This field is required')]</value>
      <webElementGuid>2d54483d-001f-4b48-a84d-6fc9e3b6a4d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
