<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AS1026- CMS Kategori Tanya 175_ext-gen1101</name>
   <tag></tag>
   <elementGuidId>fa899227-4f61-4753-beb4-40837bc14e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ext-gen1101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ext-gen1101']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57436085-5a73-4c13-b66e-d58bd2abbc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>759853bf-90c0-4a44-a702-16f19ba57fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-mask</value>
      <webElementGuid>8fa4c06a-c942-4938-8adf-d378a081da99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-gen1101</value>
      <webElementGuid>23a03a5b-ef58-46a0-8cc4-c5de2453cdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen1101&quot;)</value>
      <webElementGuid>8d50cab1-e466-41b4-83c2-53c996155dd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ext-gen1101']</value>
      <webElementGuid>a31a11b2-3dae-46a5-9869-c160e208248e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='ext-gen1018']/div[9]</value>
      <webElementGuid>9994e3e6-3ae4-49c9-971d-98a6fedebd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>a6138722-97f1-485b-a5d8-a0b8827ffbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ext-gen1101']</value>
      <webElementGuid>6d5280ff-b937-4d49-8f49-1e94b61a1a5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
