<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AS1017- CMS Tanya 175_form</name>
   <tag></tag>
   <elementGuidId>2b32d1e6-fc2c-4069-b4dc-113f3a855528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@id='form'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7482d73c-1279-475e-9fbf-79ff3b3e0372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.28.108.46:5444/smile/mod_ec/form/as1017.php?mid=624170000000000</value>
      <webElementGuid>54b53259-6867-4397-870e-2a45d2b4283d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>35160f43-704b-459a-88e0-8f0ad6db1841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5e483794-f857-4435-8d57-e5064eb0450c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>673edd19-4973-4594-a61e-572a5b9d17a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>1de049a1-e336-4c10-9e19-5d11532dbca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>17300393-d010-44f4-9de4-1d161e0c9e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/mod_ec/form/as1017.php?mid=624170000000000-innerCt&quot;)/iframe[@id=&quot;form&quot;]</value>
      <webElementGuid>d67280e2-6b47-4bef-aa62-fed39cf9af45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@id='form'])[3]</value>
      <webElementGuid>56be98d5-91dc-4c65-96e5-8575c6e21a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='/mod_ec/form/as1017.php?mid=624170000000000-innerCt']/iframe</value>
      <webElementGuid>b8817897-8d6c-40cf-a477-3cde21af9a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/div/iframe</value>
      <webElementGuid>319380e1-6fda-446c-9da1-132f57bce0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'http://172.28.108.46:5444/smile/mod_ec/form/as1017.php?mid=624170000000000' and @id = 'form' and @name = 'form']</value>
      <webElementGuid>45d0d680-5c59-4840-9f40-6f783fbb9adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@id='form'])[2]</value>
      <webElementGuid>14ebbe59-1467-4fc7-b9f4-5ab99e2f0475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/iframe</value>
      <webElementGuid>41251aee-0edf-4a60-a0af-3628c6586aa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
