<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_kategori</name>
   <tag></tag>
   <elementGuidId>7f2dfe44-b167-464a-bbb1-28f72f870be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_kategori</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_kategori']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0e36bae-1696-44ac-a3a3-fa358033d1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0590da44-ff82-4b82-b803-135e3e05d743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kategori</value>
      <webElementGuid>897847e8-0a99-4f59-80ea-ec74863a9f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_kategori</value>
      <webElementGuid>47f8e607-2da0-4702-aebf-b7d53821bb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_kategori&quot;)</value>
      <webElementGuid>a651cc37-b9cf-483a-ada7-32caf5f165e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1026- CMS Kategori Tanya 175_form</value>
      <webElementGuid>2dee5b67-d00c-44ff-964a-7ef3f7127d8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_kategori']</value>
      <webElementGuid>5b0a165f-14fe-49e5-b9b7-0e1604cf7bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSubmitCategory']/div[2]/input</value>
      <webElementGuid>25634364-439a-4d46-8ba3-fceef4bb1759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>617c9bba-b013-4560-897c-adc13f900c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_kategori' and @id = 'nama_kategori']</value>
      <webElementGuid>64d0c6cb-ace4-4918-9905-7f010b4e0433</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
