<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rule</name>
   <tag></tag>
   <elementGuidId>82620da5-fa8e-4b94-8df4-e1a92b435468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combox-inputEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combox-inputEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7d63b1c-9d96-48db-bc44-a525d2e53f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combox-inputEl</value>
      <webElementGuid>9b213140-86cd-469f-87e5-e16ccea4772d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f0f356f-7d49-4043-8187-d958e6b3accc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4133d7d2-53f7-4790-b4a9-62baa74481de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>c528aa2f-49fd-4c65-a946-38d561f0f7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bb7459d6-6bb2-4f2a-aaf9-7f8eb05051ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rule</value>
      <webElementGuid>e66dcad8-ba28-45a2-b10b-dd70b7b1d048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combox-inputEl&quot;)</value>
      <webElementGuid>23ffcf3b-1f60-4132-b252-fbb12200c8bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combox-inputEl']</value>
      <webElementGuid>ad4f8de0-e26a-47c7-8eee-6e884a3a1198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='combox-inputCell']/input</value>
      <webElementGuid>de0bad14-802a-4cfa-8775-66f74978c58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c271769d-9afe-4ec2-b0f5-0ad376b06d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combox-inputEl' and @type = 'text' and @name = 'rule']</value>
      <webElementGuid>a3977ace-d8ec-48b0-97aa-ca1bfd376425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
