<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AS1026- CMS Kategori Tanya 175_1</name>
   <tag></tag>
   <elementGuidId>a985cfe7-14d9-4cb8-b07a-c57c5e2d0b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-1032-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tab-1032-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd54c214-a5ba-4489-8907-445552df4122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-1032-btnInnerEl</value>
      <webElementGuid>dacbc701-e38d-4777-b6ab-b285f27fd062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tab-inner x-tab-inner-center</value>
      <webElementGuid>52ec445c-4561-4c3b-8229-21b1fd2ab8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>5656986f-6149-4c95-a4a1-e69fd7d6ebdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AS1026- CMS Kategori Tanya 175</value>
      <webElementGuid>358caa53-5563-44e4-a754-22b20fe0d1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1032-btnInnerEl&quot;)</value>
      <webElementGuid>13c743e1-ac3d-4dc6-95f6-632231e80929</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='tab-1032-btnInnerEl']</value>
      <webElementGuid>d92a12c9-f752-4df1-9307-e4d6e632adab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='tab-1032-btnEl']/span</value>
      <webElementGuid>08f67bae-12c4-4d3c-aed0-73cca0d40ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::span[4]</value>
      <webElementGuid>37a00e9e-8277-4017-8791-6dacb15ee010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance Management'])[1]/following::span[7]</value>
      <webElementGuid>8b8eb4ec-060b-438f-bc5a-2d670a8475f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AS1017- CMS Tanya 175'])[2]/preceding::span[3]</value>
      <webElementGuid>3f453ab7-dfed-4eee-b190-be7d4af6ccaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'tab-1032-btnInnerEl', '&quot;', ')')])[1]/preceding::span[13]</value>
      <webElementGuid>5ea56f0b-fc23-44ae-b49e-0c5536441a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span/span/span</value>
      <webElementGuid>bd79baa2-66ce-4e58-a2a1-e4264bfe5304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'tab-1032-btnInnerEl' and (text() = 'AS1026- CMS Kategori Tanya 175' or . = 'AS1026- CMS Kategori Tanya 175')]</value>
      <webElementGuid>cafe8943-f00c-4c2d-a50b-76466ff28e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
