<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New</name>
   <tag></tag>
   <elementGuidId>cee0ed6d-15ee-4fb3-838a-e96b15de8905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='AS1026 - CMS Kategori Tanya 175'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5c41580-7f78-4b08-9638-9e12ec9df4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>e3db485e-a8e8-46f5-8ae5-a2480f2a9242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;appcontent&quot;]/div[2]/div[@class=&quot;div-header-form&quot;]/div[@class=&quot;div-row&quot;]/div[@class=&quot;div-col&quot;]/div[@class=&quot;div-action&quot;]/div[@class=&quot;icon&quot;]/a[1]/span[1]</value>
      <webElementGuid>4fc06fa8-9f43-424b-b6e9-37d49723b587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1026- CMS Kategori Tanya 175_form</value>
      <webElementGuid>fd265986-b592-4b3a-b14b-99b4a0ea076f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AS1026 - CMS Kategori Tanya 175'])[1]/following::span[1]</value>
      <webElementGuid>e42adbb1-492f-416a-b277-3994f51c2018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::span[1]</value>
      <webElementGuid>0c9976be-b8ab-4002-87cf-5ef4da6ec8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New']/parent::*</value>
      <webElementGuid>710dff7d-1a77-41f7-ab16-b664e3f34e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>d8fe1926-af1d-4913-8c1c-4548d9c6d13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'New' or . = 'New')]</value>
      <webElementGuid>784ab3b7-a3e8-426d-a203-e9a1538d58d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
