<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__nama_judul</name>
   <tag></tag>
   <elementGuidId>3316f1a5-8abc-466c-b887-164f963c18dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_judul</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='nama_judul']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fb8d4732-0654-46e3-a82d-c5832e710dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>282e9b99-df67-45e5-b766-b15cd7f7577d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_judul</value>
      <webElementGuid>dc551304-26ad-4d5c-b997-a84299dfb87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_judul</value>
      <webElementGuid>c24982ac-ea61-40f1-980f-ea2350871e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>d07d1ef8-58a2-4a57-b0f8-0bde761fcb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_judul&quot;)</value>
      <webElementGuid>e1cabd84-9921-4756-8699-97ac7933fa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1017- CMS Tanya 175_form</value>
      <webElementGuid>76a83f1b-b8c0-4924-b705-6860aedabc15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='nama_judul']</value>
      <webElementGuid>a5c71a05-a170-48dc-878a-27998e114d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data_entry']/div/table/tbody/tr/td/div/textarea</value>
      <webElementGuid>a4b2d02e-9ea4-4783-a49e-af35c0072b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e2692e63-7bd9-490b-bc84-742d4f1b5cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'nama_judul' and @name = 'nama_judul']</value>
      <webElementGuid>538bfeb2-df13-4a85-bdbf-96410f24dc81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
