<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ya_status_kategori</name>
   <tag></tag>
   <elementGuidId>7de40232-00db-421f-ac7e-f79d54709805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59d28083-afe3-4c6a-9fa9-5f70507e1350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>874d879a-f945-449d-85c9-3059654d9c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_kategori</value>
      <webElementGuid>5fa03b02-3867-4d7d-bafd-57e4e6a29f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fa57ac19-6963-4b63-9cb1-b1dfe13c5d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3bb83431-68d8-4722-9942-36600160c67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no&quot;)</value>
      <webElementGuid>f5d80262-80a3-4ec7-b265-93cd772bfc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1026- CMS Kategori Tanya 175_form</value>
      <webElementGuid>61d0ab57-24fc-4fdc-9e59-a076b76acb26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no']</value>
      <webElementGuid>5ca3679a-92d3-4ce5-8517-4dccb7995c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSubmitCategory']/div[4]/div/div[2]/input</value>
      <webElementGuid>05fc5166-977c-4803-947c-c6df10063872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>4e2f2f32-7164-4e55-a90a-5c35eaf5d15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'status_kategori' and @id = 'no']</value>
      <webElementGuid>d935deb6-7e80-492b-8043-e4d17e80b060</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
