<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gambir</name>
   <tag></tag>
   <elementGuidId>cd973110-d00e-404e-bed0-d6accc7499ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;javascript:window.opener.document.formreg.kode_kabupaten_kontak.value='3171';window.opener.document.formreg.nama_kabupaten_kontak.value='JAKARTA PUSAT'; window.opener.document.formreg.kode_propinsi_kontak.value='31'; window.opener.document.formreg.nama_propinsi_kontak.value='DKI JAKARTA '; window.opener.document.formreg.kode_kecamatan_kontak.value='317101'; window.opener.document.formreg.nama_kecamatan_kontak.value='GAMBIR'; window.opener.document.formreg.kode_kelurahan_kontak.value='4621'; window.opener.document.formreg.nama_kelurahan_kontak.value='Gambir'; window.opener.document.formreg.kode_pos_kontak.value='10110'; window.close();&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87b6dcd6-27a9-45d9-8b54-f4654a74042e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cf57c559-c631-4448-b8cd-97b446f621f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:window.opener.document.formreg.kode_kabupaten_kontak.value='3171';window.opener.document.formreg.nama_kabupaten_kontak.value='JAKARTA PUSAT'; window.opener.document.formreg.kode_propinsi_kontak.value='31'; window.opener.document.formreg.nama_propinsi_kontak.value='DKI JAKARTA '; window.opener.document.formreg.kode_kecamatan_kontak.value='317101'; window.opener.document.formreg.nama_kecamatan_kontak.value='GAMBIR'; window.opener.document.formreg.kode_kelurahan_kontak.value='4621'; window.opener.document.formreg.nama_kelurahan_kontak.value='Gambir'; window.opener.document.formreg.kode_pos_kontak.value='10110'; window.close();</value>
      <webElementGuid>5d48b149-099f-473b-b8d3-3ea4e0508459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gambir</value>
      <webElementGuid>8aaadb23-9275-441d-90e6-f88736ea8787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mydata&quot;)/tbody[1]/tr[2]/td[2]/a[1]</value>
      <webElementGuid>2e63b917-acdd-4dd1-83e6-3b2c0a452e5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;javascript:window.opener.document.formreg.kode_kabupaten_kontak.value='3171';window.opener.document.formreg.nama_kabupaten_kontak.value='JAKARTA PUSAT'; window.opener.document.formreg.kode_propinsi_kontak.value='31'; window.opener.document.formreg.nama_propinsi_kontak.value='DKI JAKARTA '; window.opener.document.formreg.kode_kecamatan_kontak.value='317101'; window.opener.document.formreg.nama_kecamatan_kontak.value='GAMBIR'; window.opener.document.formreg.kode_kelurahan_kontak.value='4621'; window.opener.document.formreg.nama_kelurahan_kontak.value='Gambir'; window.opener.document.formreg.kode_pos_kontak.value='10110'; window.close();&quot;])[2]</value>
      <webElementGuid>2cb74f84-7b21-4c1b-b0c2-d2860eadf9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mydata']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>53aea780-c2a8-4428-836c-273c4a82faba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gambir')]</value>
      <webElementGuid>24594f03-2a70-4efb-b76b-8841f7e81457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Propinsi'])[2]/following::a[2]</value>
      <webElementGuid>75d5060c-7c46-4b78-acde-ff4b362de3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kabupaten'])[2]/following::a[3]</value>
      <webElementGuid>06122a80-d349-4d12-a48b-1b5600a13000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page :'])[1]/preceding::a[49]</value>
      <webElementGuid>6917c853-f789-4ac5-a8c6-79d3fc1c9806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gambir']/parent::*</value>
      <webElementGuid>89899dd9-a3e9-4ca6-b6ec-6dca1b9c38ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>62587c80-2327-4fe7-9c67-6a41dd00dd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>009acc1e-b497-4d52-98d4-ebe26cc1cbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Gambir' or . = 'Gambir')]</value>
      <webElementGuid>32cfec82-c96f-4d38-b805-d4129519b90a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
