<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kategori</name>
   <tag></tag>
   <elementGuidId>1c2af37b-ac9a-4681-a771-a37663f7aa32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kategori[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kategori[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>552cd1dc-ab74-4f0c-86d0-72d435cc24b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4dbc685b-b59a-4fd7-b278-e8303e9a5af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori[]</value>
      <webElementGuid>5880121c-9eaa-4a54-b706-f6d9d1646567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kategori required</value>
      <webElementGuid>7acb32e4-9398-46f5-be4d-31fe49204044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0baa19cb-d8d4-4f72-8a45-ed02caee5ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>844e4fdd-5f5b-46a1-927c-282e236de879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>text/csv</value>
      <webElementGuid>e069a226-ccb8-4a74-b5b5-052832e931b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('Input nama kategori.')</value>
      <webElementGuid>e9a98e40-13cc-4e4e-9e0b-95d5b7eaaa60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.setCustomValidity(''); $(this).css('background-color' , '#FFFFFF');</value>
      <webElementGuid>8ab6a91a-5923-434a-ab37-0023407b4bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;konten2&quot;)/div[@id=&quot;konten_form&quot;]/div[@class=&quot;form-row_kiri&quot;]/input[@class=&quot;kategori required&quot;]</value>
      <webElementGuid>a307bbe2-9eb7-4b22-b55a-4d7c7d2ab355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/manual/button add kategori/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1031-CMS FAQ Kategori dan Sub Kategori_form</value>
      <webElementGuid>7453fa85-c3b6-4846-b8d3-da192038b5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kategori[]']</value>
      <webElementGuid>00ca9e44-f904-45ca-a98e-da2ae37a0214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konten_form']/div[4]/input</value>
      <webElementGuid>0cc80654-013e-4a81-8449-e7b1fa7e83b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9544c106-322f-4585-ae54-4f3075587a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kategori[]']</value>
      <webElementGuid>4defd374-ad43-4b2d-b623-7542111cac01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
