<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Select Background Color_jawaban_ifr</name>
   <tag></tag>
   <elementGuidId>c9565b78-f4c4-47c8-a819-bcfab9833d67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='jawaban_ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jawaban_ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jawaban_ifr</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ddbf3957-4d1e-4f93-9551-4fc22df23312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jawaban_ifr</value>
      <webElementGuid>4bec0c20-f341-4421-9941-f672dc529729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>javascript:&quot;&quot;</value>
      <webElementGuid>381b624f-b6bb-467b-b6fc-d344319c43df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a0bd3b8a-6f7e-45e8-bf2c-f3221875a365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1449f67-bdaf-4cdd-b907-a608c2cab269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text AreaPress ALT-F10 for toolbar. Press ALT-0 for help</value>
      <webElementGuid>dd757dac-02cf-46fa-91d7-f38744d564f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jawaban_ifr&quot;)</value>
      <webElementGuid>26367de6-feac-4ec8-be2a-9ecb27672b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/Pengajuan FAQ/Data ke 1/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1032-CMS FAQ_form</value>
      <webElementGuid>f009fbe2-7701-4a39-87f5-23dda366530c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='jawaban_ifr']</value>
      <webElementGuid>6214bd9e-7e41-41ee-8c09-52d36dc51118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='jawaban_tbl']/tbody/tr[2]/td/iframe</value>
      <webElementGuid>eb71d629-25ae-42b1-bf29-502e722d4e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span/table/tbody/tr[2]/td/iframe</value>
      <webElementGuid>371b631f-7a81-4ca2-b03f-45bc0bc87a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'jawaban_ifr' and @src = 'javascript:&quot;&quot;' and @title = 'Rich Text AreaPress ALT-F10 for toolbar. Press ALT-0 for help']</value>
      <webElementGuid>4367db87-87a2-45d1-bb5c-c616bf96e373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
