<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Select Background Color_pertanyaan_ifr</name>
   <tag></tag>
   <elementGuidId>78fa973d-1a88-412f-ac5f-db6b91811d9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='pertanyaan_ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pertanyaan_ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pertanyaan_ifr</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e59fe3e9-8ff9-4c7e-b2a6-7e05753e9435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pertanyaan_ifr</value>
      <webElementGuid>c7291fe5-6f33-4e78-bed4-a2828f5e4578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>javascript:&quot;&quot;</value>
      <webElementGuid>c7b0e636-e5f2-468e-abfa-c0865ce53ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>adbece38-2d17-4f4e-a410-ec5e6596d526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6b911eb-3e11-449a-b64e-a924984c27f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text AreaPress ALT-F10 for toolbar. Press ALT-0 for help</value>
      <webElementGuid>90f42081-3612-463a-94d2-654e51093934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pertanyaan_ifr&quot;)</value>
      <webElementGuid>1b9669df-95b7-450d-a3a1-cef42a3f8594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/Pengajuan FAQ/Data ke 1/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1032-CMS FAQ_form</value>
      <webElementGuid>c088f6f6-6fda-4bcb-8e74-be1581e18c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='pertanyaan_ifr']</value>
      <webElementGuid>2aafd297-6eed-4aa8-a8ac-bb1e640ef54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pertanyaan_tbl']/tbody/tr[2]/td/iframe</value>
      <webElementGuid>ce10c107-61d9-4ebc-9a8c-1d91be87fb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7231fd72-b158-4ddc-8666-1b033b1f2c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'pertanyaan_ifr' and @src = 'javascript:&quot;&quot;' and @title = 'Rich Text AreaPress ALT-F10 for toolbar. Press ALT-0 for help']</value>
      <webElementGuid>d747315a-fdd5-4f15-8a7d-2120443887b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
