<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>3449a882-bb6f-427e-a4aa-42480fdcbb4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='mydata_grid']/tbody/tr/td/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aafce75f-f838-4a5b-9e9c-91b63bf457a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://172.28.108.46:5331/smile/mod_ec/form/as1024_campaign_notification_edit.php?kode_pengajuan=CMSP2409100019&amp;aksi='+'view'</value>
      <webElementGuid>e4607c16-7902-4b61-bbf4-6ec5fe64102a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Edit
                                        </value>
      <webElementGuid>eff5ea53-2e3e-4ca6-8e1b-793bb6cf0f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mydata_grid&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]/div[1]/a[2]</value>
      <webElementGuid>e1183916-6958-4fdf-9cf5-5bcf8011cf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Blasting Campaign/Test/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1024-BlastingCampaign_form</value>
      <webElementGuid>39c60426-01e2-4911-8bf4-727515e93a25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mydata_grid']/tbody/tr/td/div/a[2]</value>
      <webElementGuid>d9274935-e259-481e-b887-d28842be22f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>b099960a-e2e6-475a-82ce-f9e16b3860c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='||'])[1]/following::a[1]</value>
      <webElementGuid>04ba5679-615f-44ca-b333-2f2fe00266ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terkirim/Impression'])[2]/following::a[2]</value>
      <webElementGuid>ab542c59-ac82-49aa-adce-d48f1d686dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='||'])[2]/preceding::a[1]</value>
      <webElementGuid>2e0d56f2-e9c8-4437-83ff-ed5d29acfd1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hari Natal'])[1]/preceding::a[2]</value>
      <webElementGuid>4f64a850-b4ab-4ed1-9ed9-55b3d6734618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>b3364a94-d4b7-4e99-aa37-440dfe1ffcce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href=&quot;http://172.28.108.46:5331/smile/mod_ec/form/as1024_campaign_notification_edit.php?kode_pengajuan=CMSP2409100019&amp;aksi='+'view'&quot;]</value>
      <webElementGuid>58c9c726-6f52-4201-a929-e33512981bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>7ab50edf-3029-4cc2-8680-2dfef634f098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;http://172.28.108.46:5331/smile/mod_ec/form/as1024_campaign_notification_edit.php?kode_pengajuan=CMSP2409100019&amp;aksi=&quot; , &quot;'&quot; , &quot;+&quot; , &quot;'&quot; , &quot;view&quot; , &quot;'&quot;) and (text() = '
                                            Edit
                                        ' or . = '
                                            Edit
                                        ')]</value>
      <webElementGuid>f12bbca9-db33-45d0-8ee1-b523b27d27e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
