<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Memilih RoleSelamat datang user EKA DES_b574d2</name>
   <tag></tag>
   <elementGuidId>cbca15b6-417b-4f12-b0eb-0a46ef810ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-1022-innerCt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-1022-innerCt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#form-1022-innerCt</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6901cbae-4f3c-4d81-968a-bed3068298a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-1022-innerCt</value>
      <webElementGuid>a632cf50-42a0-4fbd-8fb9-e464216989c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2ac81f5d-8b49-4ae3-9fd4-cd8ac905a36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Memilih RoleSelamat datang user: EKA DESTIKA SANDAKILA, Anda melakukan koneksi ke Aplikasi SMILE dari 172.26.7.31:Pilih:</value>
      <webElementGuid>b0b7728a-4e15-410f-8ac0-09190be2627a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-1022-innerCt&quot;)</value>
      <webElementGuid>2df563fb-8d2c-4978-b2cf-fb309f4759d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='form-1022-innerCt']</value>
      <webElementGuid>b8e2eee9-fdd3-4234-ab8d-6871722bba94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='form-1022-outerCt']/div</value>
      <webElementGuid>e0fec83b-51d3-4185-804a-63aeafa5dc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Role Aplikasi'])[1]/following::div[4]</value>
      <webElementGuid>40249566-9bc3-4171-8794-2eb7133eaf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[29]</value>
      <webElementGuid>ee51fe53-b267-411b-b839-64a7a19cf6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/span/div</value>
      <webElementGuid>1e4ad766-09dc-46f2-a63c-014c104f314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'form-1022-innerCt' and (text() = 'Memilih RoleSelamat datang user: EKA DESTIKA SANDAKILA, Anda melakukan koneksi ke Aplikasi SMILE dari 172.26.7.31:Pilih:' or . = 'Memilih RoleSelamat datang user: EKA DESTIKA SANDAKILA, Anda melakukan koneksi ke Aplikasi SMILE dari 172.26.7.31:Pilih:')]</value>
      <webElementGuid>36dbc5d3-746f-491f-a87b-eb28d36a1e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
