<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AS1024-BlastingCampaign_tab-1032-closeEl</name>
   <tag></tag>
   <elementGuidId>8d30ea53-3d13-4f4d-89e3-6de9b562bf22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='tab-1032-closeEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-1032-closeEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tab-1032</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84e43aeb-be5c-4cbc-b6f5-ef0eeae1c898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-1032-closeEl</value>
      <webElementGuid>66b5021d-977c-40fd-b3b5-0b40eb4224ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>087df3ff-b86d-43ff-854e-366db4e2b5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tab-close-btn x-tab-close-btn-over</value>
      <webElementGuid>eb0f00d1-2d2e-4485-a308-159757e94951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close Tab</value>
      <webElementGuid>3a12a817-0c25-465d-a405-2875fcb16c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close Tab</value>
      <webElementGuid>8dff35ab-5bc8-4f3a-b291-8d4ad572ed27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1032-closeEl&quot;)</value>
      <webElementGuid>d68b7b1b-3e91-4a23-95a0-62e60cf53318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='tab-1032-closeEl']</value>
      <webElementGuid>9ee88b3a-e94f-4941-b91e-883f41e411f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='tab-1032']/span[2]</value>
      <webElementGuid>bfed1f00-a91f-40f2-8d04-67c2bfd7c1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span[2]</value>
      <webElementGuid>5419a8ad-979b-4762-9abe-31bb8a7467d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'tab-1032-closeEl' and @title = 'Close Tab']</value>
      <webElementGuid>09ce1806-a008-4fea-a735-3f28c8a0e6ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
