<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search By_cari2</name>
   <tag></tag>
   <elementGuidId>56eacf9c-2335-4f95-ae7f-7b65c016d081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cari2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cari2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;GO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b02373b-370e-4b16-84c2-3e8751b7c037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bb94dd3c-9894-4065-8a62-608caf6111b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cari2</value>
      <webElementGuid>5d9218e3-b7f4-40af-b2a6-0959fb2b100c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>GO</value>
      <webElementGuid>f27ae4c7-a1a7-49e4-8378-c5a45c36364a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-popup&quot;)/table[@class=&quot;caption&quot;]/tbody[1]/tr[1]/td[2]/input[2]</value>
      <webElementGuid>4c3ea8ed-5be8-40d2-9357-6251ff85f280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cari2']</value>
      <webElementGuid>3eb5ebc1-10a7-4b96-ba54-b7a723346ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-popup']/table/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>eaf5488f-d0c3-4d65-ab54-dd24a3f3af1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>954e81b6-1083-4420-b865-e01d4adc76fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'cari2']</value>
      <webElementGuid>309393c3-30a8-4aba-8f6d-f61a67082849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
