<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kategori</name>
   <tag></tag>
   <elementGuidId>4cfbc914-3a50-4c34-9ef8-ffd940bdb501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kategori[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kategori[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd4f8366-3c35-484e-86c2-3f9e597192f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d80973fd-f7fb-42b0-80e0-0fa32b8e6547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori[]</value>
      <webElementGuid>a78bc4b7-612d-4b38-8e57-ec206885af4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kategori required</value>
      <webElementGuid>2d62847b-a865-4819-aa42-efc0ef2ba245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>text/csv</value>
      <webElementGuid>a41efc7d-2250-499c-8422-fe6bec7ee809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('Input nama kategori.')</value>
      <webElementGuid>37d4600f-8063-4b9d-938c-98a0c6907cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.setCustomValidity(''); $(this).css('background-color' , '#FFFFFF');</value>
      <webElementGuid>5a669be5-4c33-4e2d-a834-5af8d2aa7aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;konten_form&quot;)/div[@class=&quot;form-row_kiri&quot;]/input[@class=&quot;kategori required&quot;]</value>
      <webElementGuid>db95a4d5-671e-40e2-b4ed-7290b2fff5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/validasi-new/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>55ba1bd2-d0a7-4c79-a02c-169c159d8678</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kategori[]']</value>
      <webElementGuid>56a19140-9163-46ed-a4ec-9acb42b36831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='konten_form']/div[4]/input</value>
      <webElementGuid>81e7c911-63a8-43c9-9533-b1290c437f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ee06c326-6f5e-41c4-9d25-fca7777c3f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kategori[]']</value>
      <webElementGuid>34238c1d-567d-4a8b-a38c-de54a28d8b47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
