<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1015202550</name>
   <tag></tag>
   <elementGuidId>4d6d28e9-be4c-456a-9847-fb4c3b4c0217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#page_item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='page_item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23762820-8391-48b3-9ea8-0a6798fe3488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>page_item</value>
      <webElementGuid>115c0e27-6aef-455d-969c-04adfba3f883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page_item</value>
      <webElementGuid>68a7edd3-63d2-41fa-89b8-b1d0f4e1a5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>filter('', '', '', '', '')</value>
      <webElementGuid>5dd91d91-a315-462a-b12b-a7ec33d1e098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									10
									15
									20
									25
									50
									</value>
      <webElementGuid>d764c8a8-396a-44e5-8ac2-0bbf37e59157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_item&quot;)</value>
      <webElementGuid>9fa6a311-d806-4fd7-9cfd-83038d6a43df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/validasi-new/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1031-CMS FAQ Kategori dan Sub Kate_6caf2b</value>
      <webElementGuid>bb5866c3-a251-4952-b182-3ed6b7fe71c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='page_item']</value>
      <webElementGuid>be1e63b2-d2e2-49f3-a2bc-a60eaf20ead1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formframe']/div/div[2]/div[3]/div/div[2]/div/select</value>
      <webElementGuid>8c60c8f4-8710-4c7e-b8bb-cfed881c8edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan item ke 1 sampai dengan 10 dari 34 items'])[1]/following::select[1]</value>
      <webElementGuid>d2823c79-6acc-4884-9fef-f8a464913baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dari 4 halaman'])[1]/following::select[1]</value>
      <webElementGuid>5b63c3e4-4714-442d-9784-8d1247bb68fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan:'])[1]/preceding::select[1]</value>
      <webElementGuid>ccde3959-de32-499d-b459-8d58d01b46b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Data Kategori'])[1]/preceding::select[1]</value>
      <webElementGuid>7ca89d2a-b22b-4024-9538-d050af51a218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>735f8817-9311-4b5b-89e7-c7870fcbb6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'page_item' and @id = 'page_item' and (text() = '
									10
									15
									20
									25
									50
									' or . = '
									10
									15
									20
									25
									50
									')]</value>
      <webElementGuid>4d7b5116-eef0-4133-b882-4c38253e6146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
