<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK_button-1005-btnIconEl</name>
   <tag></tag>
   <elementGuidId>1c4cc718-a3d8-4f9c-9e42-2aa6a36cf0d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1005-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1005-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1029e9e7-67e5-4196-b40b-0e5645a81328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>af0ad501-e7dc-47fa-bc54-1879cd746136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1005-btnIconEl</value>
      <webElementGuid>6fe98415-383c-4e9c-91f7-44d60f6e86fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>04c870ad-2581-4383-af2f-2e0a374769d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c3eff22c-dca4-4917-ad62-2ed5c3f098c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1005-btnIconEl&quot;)</value>
      <webElementGuid>d809d081-496f-44de-8f5c-8da8d4300e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnIconEl']</value>
      <webElementGuid>e3ca0712-4be6-413d-8a99-0abc228a18de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnEl']/span[2]</value>
      <webElementGuid>2e2c2458-1f5a-4c1a-8c8a-ac93777a1d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/span/span/span[2]</value>
      <webElementGuid>d8e5c797-480a-4206-ae72-393f242f6ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1005-btnIconEl']</value>
      <webElementGuid>ae8237b8-3a1c-4547-afce-b2dcb366276f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
