<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login_button-1016-btnIconEl</name>
   <tag></tag>
   <elementGuidId>29045f1b-58fc-42bc-b9b1-06fcba0fc067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1016-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1016-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>042501c8-77a1-4ad8-b508-e603a5fdb59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a8d4d77b-6807-49fd-9f26-d91277889049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1016-btnIconEl</value>
      <webElementGuid>54cdd8f7-434e-4d2f-93b3-188c3b4ee885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>6cfd7549-17be-4e36-b524-ef5fd3d6a667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e70f392d-b8aa-4380-85fe-384005be2467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1016-btnIconEl&quot;)</value>
      <webElementGuid>78c93c28-43c0-45da-84bc-cc608ea204cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1016-btnIconEl']</value>
      <webElementGuid>4241c8cd-f89a-4891-827a-a0123c6137cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1016-btnEl']/span[2]</value>
      <webElementGuid>ad44b274-6326-4280-b8d5-206aa52b737f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span/span/span[2]</value>
      <webElementGuid>d2c7fc4d-c49a-46ae-a7a9-f00997638583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1016-btnIconEl']</value>
      <webElementGuid>a4652325-e263-4510-823c-832200e9ff13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
