<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__thumbnail_dokumen</name>
   <tag></tag>
   <elementGuidId>19dd42fc-0ece-40b6-b296-9d279c8992ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thumbnail_dokumen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='thumbnail_dokumen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24e13a52-dd4c-46d0-808d-4211ccfc1bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>8bbd18be-84fc-41c6-a2eb-7463dfd827a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thumbnail_dokumen</value>
      <webElementGuid>59edec45-618d-4781-9263-1e90c9915a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thumbnail_dokumen</value>
      <webElementGuid>5f35d1c9-91c7-4318-b63d-4a8d27b13e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>90c08804-fee7-45af-a69c-05e40dfef44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fileToBase64(this)</value>
      <webElementGuid>77c3a781-fe89-4352-832b-b00d84c3ab57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thumbnail_dokumen&quot;)</value>
      <webElementGuid>c1e23d36-d62f-4852-a163-25bab06ae4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1023-Filtering Data_form</value>
      <webElementGuid>257a4c69-7dc8-40df-b3fb-84686924c68b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='thumbnail_dokumen']</value>
      <webElementGuid>137f9782-269a-4819-9179-81b716988407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='document_wrapper']/div[3]/div/input</value>
      <webElementGuid>18af084a-9750-4040-a844-83897efe30e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c25d7f4f-ba45-40c3-9b42-d3441f1fe16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'thumbnail_dokumen' and @id = 'thumbnail_dokumen']</value>
      <webElementGuid>840a1c3f-e557-4b55-900f-b7cce73ad5d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
