<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__file_dokumen</name>
   <tag></tag>
   <elementGuidId>aa30328c-7688-43ea-a9ee-3abde8b0575b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#file_dokumen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file_dokumen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bdffb53-f1d9-42fa-b784-6e735a9a7e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>08f3bdc8-5d0d-4c4c-a643-758d4d56d363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file_dokumen</value>
      <webElementGuid>ac8db3a9-981f-48be-b82e-2f81dbe8bd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_dokumen</value>
      <webElementGuid>b2f1dea3-96e6-42c9-b90b-c5e64a4d946c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*,application/pdf</value>
      <webElementGuid>5b8d2528-ed08-4508-b53a-6bf9cfe9b059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fileToBase64(this)</value>
      <webElementGuid>aad913fa-b7d0-4b27-9797-74f23473b915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file_dokumen&quot;)</value>
      <webElementGuid>6ea498f1-a680-4290-b449-94e4c663575d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1023-Filtering Data_form</value>
      <webElementGuid>3ee99122-80a7-402b-8306-913f9788fbb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file_dokumen']</value>
      <webElementGuid>cacbad94-7168-4f22-b27a-651b814a49c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='document_wrapper']/div/div/input</value>
      <webElementGuid>168426c8-8e19-41e6-bdaf-7c767e0be11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>6f6f7833-b19f-42a0-9d4d-8f0fa2206c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'file_dokumen' and @id = 'file_dokumen']</value>
      <webElementGuid>aa40d4f3-c202-4c14-96a9-653f35388991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
