<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>all</name>
   <tag></tag>
   <elementGuidId>974607dc-cccb-4792-856b-2cc7e7f47149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;All&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ca6f63f-4b1a-46b0-941b-a416da0b2ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>d58f6df6-7d3f-4a3a-9922-c9f667049586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1016bab3-5e13-44b8-80b9-594f93a2ca27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>os</value>
      <webElementGuid>4772abea-74bc-4668-a725-56978db069fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>0529b26a-1f08-47f5-805c-5823fc878865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all&quot;)</value>
      <webElementGuid>56ebd4f5-567f-4825-b1a4-f3e8d7533c9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='all']</value>
      <webElementGuid>08853832-664f-4bf1-ac4f-b2877b99619b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-popup']/table/tbody/tr/td[2]/div/div/input</value>
      <webElementGuid>753244dc-17fb-4ec8-a86d-031b402c66be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>003690d1-d831-498e-b7ef-ffec21d18ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'all' and @type = 'radio' and @name = 'os']</value>
      <webElementGuid>35e18705-cd31-46ad-8731-254062592b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
