<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_tampilkan_data</name>
   <tag></tag>
   <elementGuidId>73f443a0-9a3b-4f3b-84f9-60a151fa45c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cari2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cari2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;TAMPILKAN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ce1cc1f-a61a-4823-9b97-9dab48e29aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3e619900-96c5-45a6-b94a-030ab1998286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cari2</value>
      <webElementGuid>46ad85fe-f261-4ae1-8da5-f530e119ec98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TAMPILKAN</value>
      <webElementGuid>b43cc803-72aa-40e2-b2ab-b6abf0b71308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>fe31eaad-d167-431a-9424-a339eac5fc72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-popup&quot;)/table[@class=&quot;caption&quot;]/tbody[1]/tr[1]/td[2]/input[@class=&quot;btn green&quot;]</value>
      <webElementGuid>a7a313a1-1f45-4cc0-9321-2af203ff2891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cari2']</value>
      <webElementGuid>cab487ab-e27d-4da2-a1f7-8a5ec54ad170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-popup']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c0ba2214-ea50-4c57-8cf8-8702c7815013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>de3cf9c5-9260-488f-ba4a-17587bdff15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'cari2']</value>
      <webElementGuid>5f17845d-f2d3-49b3-b85f-549c49a0e87a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
