<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnsimpan</name>
   <tag></tag>
   <elementGuidId>881021a2-cef1-4bf3-bd52-d1cf74983d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnupload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/form/div[2]/div[4]/table/tbody/tr/td/input[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @id = 'btnupload' and @name = 'btnupload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;UPLOAD EXCEL&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25289534-9d7b-47c0-98cf-1f43fe94f1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9bf17010-8e8f-4305-b384-22398c784f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>32d3189f-296d-47e9-b9f7-f5aaed59b849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnupload</value>
      <webElementGuid>9641e067-f9b0-47b9-9da2-b39a092dda73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnupload</value>
      <webElementGuid>30be98b5-689e-4c62-8c5d-43a336f54900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UPLOAD EXCEL</value>
      <webElementGuid>659a82f7-4238-46d7-a45f-7d1b10c969b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>preload(true);</value>
      <webElementGuid>edea1536-a6bc-4a7d-a8b1-935f9321359a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-popup&quot;)/table[@class=&quot;caption&quot;]/tbody[1]/tr[1]/td[1]/input[@id=&quot;btnupload&quot;]</value>
      <webElementGuid>014adfed-fc04-4d8f-9ea9-9797a57ea08a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnupload']</value>
      <webElementGuid>7b8cebb3-c2f2-40d8-81fb-cdfa5da3d437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-popup']/table/tbody/tr/td/input[2]</value>
      <webElementGuid>cbdb85ab-5f69-47c6-b627-996081f8d89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>cbd927f7-b4bf-4810-ae65-334ff9351fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnupload' and @name = 'btnupload']</value>
      <webElementGuid>8a65b358-f0e1-4fa0-a089-45bfa3ebc566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
