<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ios</name>
   <tag></tag>
   <elementGuidId>1a0fa8e9-6441-4e8f-bf02-e247a8937c93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ios</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ios']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;IOS&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02f8d355-f65f-45aa-95bb-fd8be09490be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ios</value>
      <webElementGuid>0cc4bf60-dc38-4355-b8c5-f721dae84e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b07f85a8-8d32-42fb-8df8-73939b8c612f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>os</value>
      <webElementGuid>a04ee5a7-a7e1-4227-a3fa-b49c657fc428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ios</value>
      <webElementGuid>a6c0a33a-9606-4ce2-84d4-9790ede9d219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ios&quot;)</value>
      <webElementGuid>b888c22d-2cbd-422c-9bec-bc473f6dec82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ios']</value>
      <webElementGuid>ca823f72-b991-4139-a433-0fe939125c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-popup']/table/tbody/tr/td[2]/div/div[3]/input</value>
      <webElementGuid>92b54176-c9d6-4d1c-8c0d-253ad4590ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>56fa4136-b98f-45d1-a8b9-b672ffb88542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ios' and @type = 'radio' and @name = 'os']</value>
      <webElementGuid>ff446763-30a8-48b8-868b-02854636e5a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
