<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status_uncek</name>
   <tag></tag>
   <elementGuidId>dc623a23-6087-41e0-bce6-c03c85d3f3aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cb1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox' and @id = 'cb1' and @name = 'cb1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;cb1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac7457a3-181a-4661-aa18-f364f4e46659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0bca725d-d6c8-4a34-95f3-44ec9289c9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb1</value>
      <webElementGuid>5d3fde7c-b18f-452f-97b3-164acef78fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cb1</value>
      <webElementGuid>158238ca-7d7f-420a-86a7-7708ac1bfdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>1d7e180f-593a-42b3-b86b-de87c755098f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cekValidasi('1', this.checked);</value>
      <webElementGuid>5a5d44c4-7864-4db2-a075-d48006767bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb1&quot;)</value>
      <webElementGuid>f3753de1-5d98-46d7-82ec-25900cfd2b94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb1']</value>
      <webElementGuid>1279a693-cbfa-46e7-aef3-afcbc1760ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mydata']/tbody/tr[2]/td/div/div[2]/input</value>
      <webElementGuid>ca778c44-0bc3-4a14-b963-96f0e7e66939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div[2]/input</value>
      <webElementGuid>2594f95a-e2b0-4fe2-876c-0492c8c01e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cb1' and @name = 'cb1']</value>
      <webElementGuid>571d69a0-b276-4ad6-acb5-bd8db9e4c4ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
