<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes_button-1006-btnIconEl</name>
   <tag></tag>
   <elementGuidId>c9a88cfd-399c-4153-97a5-f251018a5c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1006-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-1006-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2bf3dfce-30a9-42e2-a123-a22d0b7f25e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1efb136a-d8f5-40eb-ad08-fe81e4fa6c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1006-btnIconEl</value>
      <webElementGuid>0b1c9c6e-87ab-4280-b6dd-c4d4008b102d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>d91eb5bc-def7-4ef4-96fc-e967af57711c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f3936f48-3bd7-4909-93dc-fd454b0462b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1006-btnIconEl&quot;)</value>
      <webElementGuid>be6d712f-18da-457f-ae53-8dddf303af9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1006-btnIconEl']</value>
      <webElementGuid>b00418eb-a088-43b8-b479-f58cedc656f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1006-btnEl']/span[2]</value>
      <webElementGuid>1d55aa37-77d6-4795-a848-24d5d1d511f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a[2]/span/span/span[2]</value>
      <webElementGuid>2e775165-008d-44be-a428-b496073c8e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1006-btnIconEl']</value>
      <webElementGuid>78220238-349c-4910-b9be-300396898cf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
