<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih Kategori --</name>
   <tag></tag>
   <elementGuidId>bce0e133-68ee-4867-a946-d087abac631b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-kategori-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-kategori-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77256749-0dd6-4ca8-94b1-8d552f028714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>726ba5d1-3b78-40c7-8498-091f074df37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-kategori-container</value>
      <webElementGuid>5aad338c-c382-4404-9b78-e20357878f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b9fc9b8f-7f64-4b45-aaba-597cb44609cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c3f0da16-35f1-4a95-bf7c-4db5188b9223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih Kategori --</value>
      <webElementGuid>8eed3b09-1eb4-4678-af0b-75ed76d173da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kategori --</value>
      <webElementGuid>d8e806bb-5c82-4359-adff-68f07c4c9ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-kategori-container&quot;)</value>
      <webElementGuid>8b5db196-103f-4745-840c-4a971698be46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/AS1017 - NEW - VIDEO/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1017- CMS Tanya 175_form</value>
      <webElementGuid>8e553190-15da-403f-a993-8c4dc3f13f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-kategori-container']</value>
      <webElementGuid>e9c34bae-0678-4fe9-8495-71a9cc6e2924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data_entry']/div/table/tbody/tr/td/div[3]/span/span/span/span</value>
      <webElementGuid>c6fb9e8c-3018-4ba2-90ef-3acc0098a851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[4]</value>
      <webElementGuid>bd392e38-2321-4891-914e-ca123bd78845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[3]</value>
      <webElementGuid>b21ce612-757d-4569-b49b-cb975dae8d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>814efdd8-d8b6-4d16-a2f5-f4917da0b007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-kategori-container' and @title = '-- Pilih Kategori --' and (text() = '-- Pilih Kategori --' or . = '-- Pilih Kategori --')]</value>
      <webElementGuid>61ab8162-f0e7-4ce5-be78-ab40b3815a5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
