<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes_button-1006-btnIconEl</name>
   <tag></tag>
   <elementGuidId>5b6aef95-a8f0-4910-a54c-76dadf15e633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1006-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1006-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>30479e70-f88b-41b5-8bbc-8c507795114a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>774aa45c-1a65-4bf0-b885-6b1ec8ddbe76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1006-btnIconEl</value>
      <webElementGuid>77376b27-ec05-4a7d-a3dd-ebb2de4384bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>8fa387a8-c2b4-4619-9a89-5161cbe7051c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>447cfe09-adf9-4914-8c00-f6ba78e1491e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1006-btnIconEl&quot;)</value>
      <webElementGuid>05b17113-8add-4903-b8a2-2f21e19786a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1006-btnIconEl']</value>
      <webElementGuid>91a38c9d-6cc8-49d0-9439-648014177823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1006-btnEl']/span[2]</value>
      <webElementGuid>1dbc47b8-ca2e-4428-8df2-fffb81b981ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a[2]/span/span/span[2]</value>
      <webElementGuid>3f440529-e1d9-4647-beb0-6813cec294e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1006-btnIconEl']</value>
      <webElementGuid>29606d80-8afe-464c-922b-6ea399da291f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
