<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_AS1024-BlastingCampaign_form</name>
   <tag></tag>
   <elementGuidId>24e20181-37f2-438c-90fa-3464732e7f4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//iframe[@id='form'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;form&quot;] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>64548ce8-9b25-4693-a5ae-b8806c181f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.28.108.46:5331/smile/mod_ec/form/as1025.php?mid=624250000000000</value>
      <webElementGuid>f4b07e4f-442e-486e-a3e3-e6aea0a517d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d93064c3-d0cd-4a42-930b-79a555c76fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>9acf5fb6-40b8-4395-850b-61f055db1ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fdc8ec14-e24c-40fa-8339-17b6c88179cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>9ed0ce39-c570-4068-acb1-2bf02e544e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>2c4f9b78-1210-44e1-9b90-e81f176d4458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/mod_ec/form/as1025.php?mid=624250000000000-innerCt&quot;)/iframe[@id=&quot;form&quot;]</value>
      <webElementGuid>7ae8c0d6-b3f3-45c2-9776-ca69246642fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//iframe[@id='form'])[2]</value>
      <webElementGuid>799dbd0c-8e21-47da-a123-adefdee0fb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='/mod_ec/form/as1025.php?mid=624250000000000-innerCt']/iframe</value>
      <webElementGuid>41ad2180-fd54-4d86-b411-c84f4d6fd83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/iframe</value>
      <webElementGuid>6a897d3c-7ba5-4a86-8960-6dbb51ad3a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'http://172.28.108.46:5331/smile/mod_ec/form/as1025.php?mid=624250000000000' and @id = 'form' and @name = 'form']</value>
      <webElementGuid>23f1aa82-191e-4949-b144-a4e2f290b513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
