<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih Tahun --</name>
   <tag></tag>
   <elementGuidId>51fba230-0700-4302-8fa0-609490051b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-lov_tahun-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-lov_tahun-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;-- Pilih Tahun --&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72197afc-3755-4aa4-9421-05c3a00a41fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7bbbd53a-baad-49ca-a14b-65102e924963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-lov_tahun-container</value>
      <webElementGuid>23a11aa6-f92d-46c7-ab09-66ac747e8916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d4b2bb9a-e7f5-4728-b197-57433ddabc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f9b76a1c-beab-4d4e-b318-e5503c49c77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih Tahun --</value>
      <webElementGuid>14e1ed1a-0b5a-486a-ae63-0df84ce12019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Tahun --</value>
      <webElementGuid>18b0411e-acb3-442b-8e11-bd62b3fb1a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-lov_tahun-container&quot;)</value>
      <webElementGuid>cfe43489-f306-49e2-8cb1-514e7b2205eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Report Blasting Campaign/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1025-Report BlastingCampaign_form</value>
      <webElementGuid>1b09338a-c33e-4dd2-a55c-ae0239f5a055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-lov_tahun-container']</value>
      <webElementGuid>973b6b86-1a37-4934-9669-d5e80f8d9b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldsetDataUtama']/div/div/div[3]/span[2]/span/span/span</value>
      <webElementGuid>181b36bd-0713-4e82-a978-2337ed6caed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun :'])[1]/following::span[4]</value>
      <webElementGuid>0af01aec-5caa-44b6-aa1a-4d51b7c83994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan'])[1]/following::span[5]</value>
      <webElementGuid>c6c69a2d-6e94-44c5-b283-dc1f6e6a204b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Blasting/Campaign :'])[1]/preceding::span[3]</value>
      <webElementGuid>69f57ac2-db2d-469d-94eb-981a4b59cd6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='selamat HUT BPJSTK'])[2]/preceding::span[4]</value>
      <webElementGuid>1a3cbd6c-1e13-4348-8149-f279f1e88cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span</value>
      <webElementGuid>5cb8fd89-a487-43c9-aa51-4d6f6b08feac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-lov_tahun-container' and @title = '-- Pilih Tahun --' and (text() = '-- Pilih Tahun --' or . = '-- Pilih Tahun --')]</value>
      <webElementGuid>4cf4395e-01e3-4567-9119-314739aa3b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
