<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kategori</name>
   <tag></tag>
   <elementGuidId>fa26db92-f25f-48a2-9129-52837a421004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='kategori[]'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c4e8e76-03dc-4b10-bac1-abe8cfb70b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f5d7103-c9e4-4c89-894d-b5e05a7948e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kategori[]</value>
      <webElementGuid>60073e12-02ce-45ce-9f27-4cb784e7277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kategori required</value>
      <webElementGuid>fa23ffd3-a3f7-42ce-897e-74f0c5fc27f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>text/csv</value>
      <webElementGuid>19a6c13b-c7ab-49cf-a952-5a8f287ad967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('Input nama kategori.')</value>
      <webElementGuid>9bf87428-d624-423e-be9a-1187da3aaca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.setCustomValidity(''); $(this).css('background-color' , '#FFFFFF');</value>
      <webElementGuid>05861632-f101-40e6-9c70-9f23ffeffe24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;konten2&quot;)/div[@id=&quot;konten_form&quot;]/div[@class=&quot;form-row_kiri&quot;]/input[@class=&quot;kategori required&quot;]</value>
      <webElementGuid>df77b393-24cc-4d08-bcec-0239e00b0d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/1 kategori/manual/input4/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1031-CMS FAQ Kategori dan Sub Kategori_form</value>
      <webElementGuid>ced148da-dbab-4dde-93f7-cdfc0f1c0828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='kategori[]'])[4]</value>
      <webElementGuid>a2eb7d15-f38a-434d-b9e8-a824f4e21d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='konten_form']/div[4]/input)[4]</value>
      <webElementGuid>b6d536f5-e2db-4d0e-9372-14ab94d3cc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>b91ccec9-476c-4901-9184-72e5f7cdb30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kategori[]']</value>
      <webElementGuid>eb7101be-5be6-4a49-a0cd-d703f4590a1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
