<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1ef1037c-0a75-467d-acec-538185869a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='img_kode_pos_kontak']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_kode_pos_kontak > img[alt=&quot;Cari Peserta&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3d85f73b-515f-4e2b-b2e0-ed4acaff3a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/help.png</value>
      <webElementGuid>7073c345-4da5-43ef-b843-f448b6663ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cari Peserta</value>
      <webElementGuid>10293263-b2a8-4d60-8cfb-e68e45001f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80cd721c-d663-4b26-9e9b-2c69fb0f6c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>03ab5fce-095a-4341-a30d-5634d70f9005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_kode_pos_kontak&quot;)/img[1]</value>
      <webElementGuid>66dac43d-7a8e-4b71-a38e-cac2fa05536c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/beasiswa/manual/Page_SMILE - Sistem Informasi Perlindungan Pekerja (46)/iframe_AS1014-Perekaman Data Biometrik Pelapor_form</value>
      <webElementGuid>c699122f-9c2d-46f7-8308-1ab5da0adf66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='img_kode_pos_kontak']/img</value>
      <webElementGuid>9e301da7-e522-4862-a818-18f50d971473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Cari Peserta'])[2]</value>
      <webElementGuid>2a641b1e-5949-4c6a-9527-006a0d245ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[4]/a/img</value>
      <webElementGuid>a656f1d2-0c85-411a-8326-b1c5aca79229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../images/help.png' and @alt = 'Cari Peserta']</value>
      <webElementGuid>3cdfb371-1ec5-4880-93ac-999b10d56bee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
