<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search By_searchtxt</name>
   <tag></tag>
   <elementGuidId>11becef2-0212-4dc7-9720-8f9d70157c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchtxt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchtxt&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2721983a-b095-41b5-99b6-a4a3b3a9b6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>014476c1-18ca-446d-9d1a-cc61500c4e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchtxt</value>
      <webElementGuid>0185d9ea-4988-45c2-ad6f-ce775023abe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>74980c81-d217-4e58-837c-a2abd506fad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-popup&quot;)/table[@class=&quot;caption&quot;]/tbody[1]/tr[1]/td[2]/input[1]</value>
      <webElementGuid>05d954fc-3b4f-478f-83ac-02be55076ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchtxt']</value>
      <webElementGuid>1e1c5e1f-785a-4b7b-83cd-5b735aa61efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-popup']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>cddf5b97-7eb6-4367-8ffa-ca073d79ae94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a88dc2f7-d1e4-4ccb-8a21-526ec437783e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchtxt']</value>
      <webElementGuid>f90563b1-c26a-47f6-aeb3-2167a4abfb0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
