<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__login</name>
   <tag></tag>
   <elementGuidId>cbf2cdf9-d64f-43ba-a5a5-8201e1dd22de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userlogin-inputEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userlogin-inputEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db7fe795-cab9-4196-9e56-c797d948dc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userlogin-inputEl</value>
      <webElementGuid>9a119725-f3ff-49d3-a9f6-59d245ed85e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3be060f-533a-47a2-a6e3-293c0b70e180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>52dc114d-344d-4085-b838-217cfe23dfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1bca1088-6a14-488f-ba58-7f83c204a009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>c515d4b4-dbc0-4017-a8e6-3892c0dc537c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-required-field x-form-text x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>a88f6a41-f758-4ec0-bc11-0b0c3504192d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4d4e017b-9f38-4db8-b2b8-bfcd33513974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userlogin-inputEl&quot;)</value>
      <webElementGuid>39eb513d-18fb-460c-ac4a-26a902974ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userlogin-inputEl']</value>
      <webElementGuid>27e71ec3-872b-418d-a2c5-03fbc68d3625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='userlogin-bodyEl']/input</value>
      <webElementGuid>d2e1e834-baf4-45d5-a71a-8f323657b118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a4dbf78d-e6cd-4caf-8068-dbaee6c63fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userlogin-inputEl' and @type = 'text' and @name = 'login']</value>
      <webElementGuid>754c549e-8e73-451e-9fa3-8b927d4fc3b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
