<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Pilih Kategori --</name>
   <tag></tag>
   <elementGuidId>f805618b-2a6b-4ff4-9605-ffc4128e30ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-kategori-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-kategori-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49dc82bb-eec4-4dd5-9bb3-0b082e5cf001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>29fe36a2-0083-486b-bd18-95a6dac4e3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-kategori-container</value>
      <webElementGuid>15bde7c6-0b90-4d93-af55-2ef2bf87a246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2e425599-b123-4c27-91f6-78f3a94387de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>354a5da5-7dfa-4879-aad8-493aa024aecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih Kategori --</value>
      <webElementGuid>a64d06c5-69ce-43d4-85fa-0f0bcfe505cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Kategori --</value>
      <webElementGuid>8747aab7-51d5-4eee-91bf-6b76514854de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-kategori-container&quot;)</value>
      <webElementGuid>ff917b0f-4cb1-496e-bc4f-d16eb1bfba99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/175/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1017- CMS Tanya 175_form</value>
      <webElementGuid>6a93af6c-e96f-4a86-9666-0449cde79596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-kategori-container']</value>
      <webElementGuid>7c053a19-6fa0-4355-88e4-da48f949d699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data_entry']/div/table/tbody/tr/td/div[3]/span/span/span/span</value>
      <webElementGuid>b402512b-43ba-4246-891a-2aa84e02136c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[4]</value>
      <webElementGuid>23bc1552-2356-4483-b858-708f7d7a705d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[3]</value>
      <webElementGuid>0e66f243-e6e1-4807-bdb9-15676bc81770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>0190d2f9-a16d-44d1-a8ad-b1f146d9f35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-kategori-container' and @title = '-- Pilih Kategori --' and (text() = '-- Pilih Kategori --' or . = '-- Pilih Kategori --')]</value>
      <webElementGuid>6ade1424-9bec-4422-b0c0-bc17fc7ebc55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
