<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PilihBatal</name>
   <tag></tag>
   <elementGuidId>7ad1c7b6-b3d4-47c4-9026-fa1a902e5c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toolbar-1025-innerCt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toolbar-1025-innerCt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#toolbar-1025-innerCt</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aee6b748-cb1d-4954-893f-2effb84420e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toolbar-1025-innerCt</value>
      <webElementGuid>0663120d-d789-47ca-a4b7-9c77beb55083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner </value>
      <webElementGuid>d0e0b802-8364-4f91-bdb8-e66c87923a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bfd5e980-60e0-4e4b-938f-74766ec63ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PilihBatal</value>
      <webElementGuid>510ca5fe-63d9-4b5f-8c19-c94ad2a4bedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toolbar-1025-innerCt&quot;)</value>
      <webElementGuid>ecb9a299-9c64-491f-8ca6-ce6af803d1b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toolbar-1025-innerCt']</value>
      <webElementGuid>9ca65eba-1d6c-493e-9dd5-2c29909a30f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toolbar-1025']/div</value>
      <webElementGuid>d3f65172-2f6b-4308-9e0a-5a2f3c10b91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/following::div[4]</value>
      <webElementGuid>2f1134a4-f422-4690-b4ea-017ca8bcf913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>fad3698c-ca8e-4df6-b175-8b360e022f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toolbar-1025-innerCt' and (text() = 'PilihBatal' or . = 'PilihBatal')]</value>
      <webElementGuid>18a2fa3c-46d5-4915-9551-55f82011e247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
