<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sukses Pengajuan Tambah Konten FAQ, Kod_3d545b</name>
   <tag></tag>
   <elementGuidId>9792882c-6629-47e8-a942-cba64328018b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='messagebox-1001-displayfield-inputEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#messagebox-1001-displayfield-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sukses Pengajuan Tambah Konten FAQ, Kode Pengajuan: `FAQ250203033`&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f45d170e-a3d0-4203-ba9b-184d39cb280b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messagebox-1001-displayfield-inputEl</value>
      <webElementGuid>6da86a1f-d8f5-4f33-a8fc-a6aa05a4bd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>cac34f90-6aa3-4305-8c18-44bf792e0300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-display-field</value>
      <webElementGuid>00efc1df-027b-42f7-b846-07d97515554d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sukses Pengajuan Tambah Konten FAQ, Kode Pengajuan: `FAQ250203033`</value>
      <webElementGuid>54689c37-c9d3-4e01-814a-d2d97ae5d775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messagebox-1001-displayfield-inputEl&quot;)</value>
      <webElementGuid>d0cdb5c0-ff95-485b-9f30-d62da3b9780b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='messagebox-1001-displayfield-inputEl']</value>
      <webElementGuid>bef0350e-5f37-4cec-aa80-75421273f50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='messagebox-1001-displayfield-bodyEl']/div</value>
      <webElementGuid>8945bb22-99ef-4c3f-8b9e-456527c8d57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perhatian'])[1]/following::div[11]</value>
      <webElementGuid>d747b7e8-e5fc-4423-a45d-1169945e1d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[5]</value>
      <webElementGuid>e029d2e6-d84e-440d-ac97-fafe79911336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::div[5]</value>
      <webElementGuid>f43a731d-6cfe-4dfa-9dce-6a9af51e237d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sukses Pengajuan Tambah Konten FAQ, Kode Pengajuan: `FAQ250203033`']/parent::*</value>
      <webElementGuid>64d55cd7-880a-4700-9368-a2e73bf20089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>3c8ee767-ddad-4880-9456-56d8ea9b0d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'messagebox-1001-displayfield-inputEl' and (text() = 'Sukses Pengajuan Tambah Konten FAQ, Kode Pengajuan: `FAQ250203033`' or . = 'Sukses Pengajuan Tambah Konten FAQ, Kode Pengajuan: `FAQ250203033`')]</value>
      <webElementGuid>8dc63071-529f-445b-bf65-4f68a41e009e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
