<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__status_approval</name>
   <tag></tag>
   <elementGuidId>53e68743-3c0b-476f-8120-268ecd53866f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ya</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ya']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Verifikasi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20c306cb-7786-4667-b240-0b3fd10c5514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>67eb08db-39b8-46cc-8f42-393f409f107e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_approval</value>
      <webElementGuid>37b62453-f505-4718-b49f-90129ffc4a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ya</value>
      <webElementGuid>4ae3a349-5069-468e-9058-b6479e75c385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-cursor</value>
      <webElementGuid>dd8e842c-747c-4532-b8a4-1447fb8ce339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ya</value>
      <webElementGuid>c9f5c8f4-807e-4901-97d2-160debcc3e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ya&quot;)</value>
      <webElementGuid>9f956b73-04e4-4f2e-a6f9-4514225c74cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/Pengajuan FAQ/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1034- Approval Pengajuan Penyesuai_ebf016</value>
      <webElementGuid>d2db8c41-749d-4a0d-be45-0d014caee676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ya']</value>
      <webElementGuid>6ed27b1a-4615-4324-95d5-109191fd1f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='approval_section']/div/div/div/input</value>
      <webElementGuid>ae3ee8ca-571a-4b27-b032-bdaf4baed835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>990ed885-8339-483e-b5bf-738d6e5f9b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'status_approval' and @id = 'ya']</value>
      <webElementGuid>7689f4a3-e2f2-4e3c-ac2b-66bb62adbc89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
