<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_x_search_by</name>
   <tag></tag>
   <elementGuidId>f504a2a4-42d8-497f-b525-0f470b73915e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_by</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_by']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cari ID Pengajuan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce7dbd22-348b-43e6-9a47-697836dce31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6a2a2f4-df06-4670-9481-c59da21d33ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari ID Pengajuan</value>
      <webElementGuid>70c4127f-0226-4d11-b272-ff1d31008636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_by</value>
      <webElementGuid>b85a7841-c00b-4a79-aff8-fde0811437e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_by</value>
      <webElementGuid>aa8d233f-97a0-4fac-a68a-1ff51a12998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_by&quot;)</value>
      <webElementGuid>c4785945-5b44-40b2-a226-1978a5ef73fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Konten faq/Pengajuan FAQ/Page_SMILE - Sistem Informasi Perlindungan _1e51ce/iframe_AS1034- Approval Pengajuan Penyesuai_ebf016</value>
      <webElementGuid>d566c5a9-d843-4f3a-bf3e-fd84398aaacd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_by']</value>
      <webElementGuid>77d23848-2658-4e18-b026-0934286aed9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>4b3b75fb-20d2-4843-89a1-d775bda92769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cari ID Pengajuan' and @name = 'search_by' and @id = 'search_by']</value>
      <webElementGuid>e0b95447-7a36-4790-b8e8-41399e93af8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
